"use strict";
var e=require("../@babel/runtime/helpers/typeof"),t=require("../config.js"),r=function(e,t){return(Array(t).join(0)+e).slice(-t)},n=function(e,t){for(var r in t)e[r]&&"[object Object]"===e[r].toString()?n(e[r],t[r]):e[r]!=t[r]&&"function"!=typeof e[r]&&(e[r]=t[r]);
return e};
var o=function(e){return(e=e.toString())[1]?e:"0"+e};
module.exports={formatTime:function(e){var t=e.getFullYear(),r=e.getMonth()+1,n=e.getDate(),a=e.getHours(),i=e.getMinutes(),u=e.getSeconds();
return[t,r,n].map(o).join("/")+" "+[a,i,u].map(o).join(":")},mTime:function(e){var t,r,n,o,a,i,u,c=arguments.length>1&&void 0!==arguments[1]&&arguments[1];
return r=(t=e?new Date(1e3*e):new Date).getFullYear(),n=t.getMonth()+1,o=t.getDate(),a=t.getHours(),i=t.getMinutes(),c?r+"-"+(n<10?"0"+n:n)+"-"+(o<10?"0"+o:o)+" "+(a<10?"0"+a:a)+":"+(i<10?"0"+i:i)+":"+((u=t.getSeconds())<10?"0"+u:u):r+"-"+(n<10?"0"+n:n)+"-"+(o<10?"0"+o:o)+" "+(a<10?"0"+a:a)+":"+(i<10?"0"+i:i)},themeUrl:function(e){var r=!(arguments.length>1&&void 0!==arguments[1])||arguments[1];
return r?t.host+"/template/theme2/images/"+t.projectId+"/"+e:t.host+"/template/theme2/images/"+e},dataUrl:function(e){return t.host+"/data/wxsamll/"+t.projectId+"/"+e},getYmd:function(e){var t=new Date;
return t.setDate(t.getDate()+e),t.getFullYear()+r(t.getMonth()+1,2)+r(t.getDate(),2)},padNum:r,apiUrl:function(){return t.api},deleteArrayItem:function(e,t){var r=e.indexOf(t);
return r<0||e.splice(r,1),e},deleteArrayItemByCall:function(e,t){var r=e.findIndex(t);
return console.log("deleteArrayItemByCall idex",r),r<0||e.splice(r,1),e},getTime:function(){return Math.round((new Date).getTime()/1e3)},ajaxMsg:function(e,t,r){return{code:e,msg:t,data:r}},getStruct:function(t,r){var n=arguments.length>2&&void 0!==arguments[2]?arguments[2]:null;
if(!t||!r||"string"!=typeof r||"object"!=e(t))return n;
var o=r.split("."),a=null,i=t;
for(var u in o){if(a=o[u],"object"!=e(i)||void 0===i[a])return n;
i=i[a]}return i},getConfig:function(){return t},pageParams:function(t){var r=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"";
if(r){if("object"==e(r)){var n=[];
for(var o in r)if(r.hasOwnProperty(o)){var a=r[o];
n.push(o+"="+a)}r=n.length>0?n.join(","):""}r="?"+r}return"../".concat(t,"/").concat(t)+r},redirectToPage:function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"";
wx.redirectTo({url:this.pageParams(e,t)})},navigateToPage:function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:"";
wx.navigateTo({url:this.pageParams(e,t)})},checkRedirect:function(){var e=getApp();
e?e.globalData.userInfo||this.redirectToPage("login"):console.error("app object not exist")},showError:function(e){var t=arguments.length>1&&void 0!==arguments[1]?arguments[1]:1500;
wx.showToast({title:e,icon:"none",image:"",duration:t})},ext:function(e){var t=e.lastIndexOf(".");
return e.substr(t+1)},merge:n};
