"use strict";
require("../../@babel/runtime/helpers/Objectvalues");
var t,o=require("../../@babel/runtime/helpers/toConsumableArray"),e=(t=require("wxmp-rsa"))&&t.__esModule?t:{default:t};
var n=require("../../config"),a=getApp();
Page({data:{isDebug:!1,isAuth:!1,hasSign:!1,signResult:!0,uuids:[],tip:"请开启蓝牙进行设备签到",url:n.host,msg:"",t:"",time:"",version:a.globalData.version,location:{},foundBeacons:[],hideLoadingTimer:null},onLoad:function(t){this.checkEnv(),(t.t||null)&&(this.setData({t:t.t}),this.verifSch(t))},checkEnv:function(){var t=this;
wx.openBluetoothAdapter({success:function(o){wx.getLocation({fail:function(o){t.alert("定位不可用","请检查定位功能是否打开且已授权",t.checkEnv)}})},fail:function(o){console.log(o),t.alert("蓝牙不可用","请检查蓝牙是否打开且已授权",t.checkEnv)}})},tapAuth:function(){this.data.isDebug?wx.navigateTo({url:"./blue?t=b9e8d1e1f7d55ad63e2bcbc6933cda983645569267ab4d0b"}):wx.navigateTo({url:"./auth"})},tapSignIn:function(){this.data.foundBeacons.length<=0?this.getBeacon():(this.loadingStart({title:"正在签到，请耐心等待"},{title:"签到失败",showCancel:!1,content:"请检查蓝牙是否正常后重试"},6e4),this.signIn())},verifSch:function(t){var o=this;
wx.request({url:"".concat(o.data.url,"index.php/wxApp/devices.html"),data:t,header:{"content-type":"application/x-www-form-urlencoded"},method:"POST",success:function(t){var e=t.data;
0==e.code?e.data.devices.length>0?(o.setData({uuids:e.data.devices,isAuth:!0}),o.getDeviceInfo()):wx.showModal({title:"提示",content:"当前学校暂未开通蓝牙签到功能",showCancel:!1,success:function(t){t.confirm}}):wx.showModal({title:"提示",content:e.msg,success:function(t){t.confirm||t.cancel}})},fail:function(t){console.log(t),wx.showToast({title:t.errMsg,icon:"none",duration:3e3})}})},getDeviceInfo:function(){this.getLocaton(),this.getBeacon()},getLocaton:function(){this.data.location=[],console.log("开始获取定位信息");
var t=this;
wx.getLocation({type:"gcj02",isHighAccuracy:!0,success:function(o){var e=[o.latitude,o.longitude];
t.data.location=e,console.log("获取定位信息成功:"+JSON.stringify(o))},fail:function(o){console.log("获取定位信息失败:"+JSON.stringify(o)),t.alert("位置信息获取失败","请打开定位功能重试",t.getLocaton)}})},getBeacon:function(){this.stopSearch(),this.data.foundBeacons=[],console.log("开始获取蓝牙信标");
var t=this;
this.loadingStart({title:"正在搜索蓝牙设备，请稍后"},{title:"查找蓝牙设备超时",showCancel:!1,content:"请确认您在蓝牙签到区域内重试",success:function(o){o.confirm&&t.getBeacon()}},5e3),wx.openBluetoothAdapter({success:function(){console.log("初始化蓝牙成功"),console.log(t.data.uuids),wx.startBeaconDiscovery({uuids:o(t.data.uuids),success:function(){console.log("蓝牙设备搜索启动成功");
var o=Date.now();
wx.onBeaconUpdate((function(e){console.log("蓝牙设备监听成功"),Date.now()-o<3e3||wx.getBeacons({success:function(o){var e=o.beacons;
if(e.length<=0)return t.stopSearch(),void t.alert("未找到蓝牙签到设备","请确认重新尝试",t.getBeacon);
console.log("获取蓝牙信标结束"),console.log(e),t.setData({foundBeacons:e}),t.stopSearch(),t.data.hasSign&&!t.data.signResult&&t.tapSignIn()},fail:function(o){console.log("获取蓝牙设备失败:"+JSON.stringify(o)),t.stopSearch(),t.alert("获取蓝牙设备失败","请检查蓝牙后重试("+o.errCode+")",t.getBeacon)}})}))},fail:function(o){console.log("搜索蓝牙设备失败:"+JSON.stringify(o)),t.stopSearch(),11005===o.errCode?t.alert("搜索蓝牙设备失败","将重启程序重新尝试",(function(){console.log("准备跳转"),wx.restartMiniProgram({path:"/pages/blue/blue"})})):t.alert("搜索蓝牙设备失败","请检查蓝牙后重试("+o.errCode+")",t.getBeacon)}})},fail:function(o){console.log("蓝牙初始化失败:"+JSON.stringify(o)),t.alert("蓝牙初始化失败","请检查蓝牙后重试("+o.errCode+")",t.getBeacon)}})},signIn:function(){console.log("开始签名请求");
var t=this,o=this.fiterBeacons(this.data.foundBeacons);
console.log("开始签名请求"),wx.request({url:"".concat(t.data.url,"index.php/wxApp/getTime.html"),method:"GET",success:function(n){var a=n.data,c=new e.default;
c.setPublicKey("-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0dmmkW4xPa+HhBTyaa0dgAb0fVZRS67jK4y15BQthjJ/ZuUZQmrbGqhG7rwnxfm7g+nFH9zEyRU5KLX3ty9jpNrPjyg7FBF9OvBDYHEt83b77W3mfBjpmoTJOt27E7RZ4InHqJQjqSEo4bw1PDz2OBmtlNIlXMu0VA8I0Bh39hBBnm0oouRV7FdqEzAp8nsF7a3VuBYpx9xek+cRVip0pMXI1AXM6bmyWWNzV0oikQW4ZIbutgDziTMeW28zl/hRbW9Ht34w0sWYyxumuLr1qweW3qnxycn3zn47weFYe6nJp71z+lgVtNTGtowNPPqBLXqusvwf+uNhSy1wKQFpUwIDAQAB-----END PUBLIC KEY-----");
var i=c.encryptLong(a.toString());
t.signInNext({t:t.data.t,devices:t.base64Encode(JSON.stringify(o)),location:t.base64Encode(JSON.stringify(t.data.location)),pass:i})}})},signInNext:function(t){console.log("开始签到请求:"+JSON.stringify(t));
var o=this;
wx.request({url:"".concat(o.data.url,"index.php/wxApp/sign.html"),data:t,header:{"content-type":"application/x-www-form-urlencoded"},method:"POST",success:function(t){console.log("签到请求成功:"+JSON.stringify(t.data));
var e=t.data;
0==e.code?o.setData({msg:e.msg,hasSign:!0,signResult:!0}):o.setData({msg:e.msg,hasSign:!0,signResult:!1})},fail:function(t){console.log("签到请求失败:"+JSON.stringify(t)),o.setData({hasSign:!1}),wx.showToast({title:t.msg,icon:"none",duration:3e3})},complete:function(){o.loadingEnd(),o.setData({foundBeacons:[]})}})},stopSearch:function(){wx.offBeaconUpdate(),wx.offBeaconServiceChange(),wx.stopBeaconDiscovery({success:function(t){console.log("stopBeaconDiscovery ok")},fail:function(t){console.log("stopBeaconDiscovery fail"),console.log(t)}}),wx.closeBluetoothAdapter({success:function(t){console.log("closeBluetoothAdapter ok")},fail:function(t){console.log("closeBluetoothAdapter fail")}}),this.loadingEnd(),console.log("停止蓝牙搜索搜索")},loadingStart:function(t,o){var e=arguments.length>2&&void 0!==arguments[2]?arguments[2]:1e4,n=this;
wx.showLoading(t),this.hideLoadingTimer=setTimeout((function(){n.loadingEnd(),wx.showModal(o)}),e)},loadingEnd:function(){wx.hideLoading(),clearTimeout(this.hideLoadingTimer)},onShareAppMessage:function(){},alert:function(t,o,e){wx.showModal({title:t,content:o,showCancel:!1,success:function(t){t.confirm&&e()}})},getAverage:function(t,o){var e=t.slice(-o);
return e.reduce((function(t,o){return t+o}),0)/e.length},fiterBeacons:function(t){var o=t.reduce((function(t,o){var e="".concat(o.uuid,"-").concat(o.major,"-").concat(o.minor);
return t[e]||(t[e]=[o.uuid,o.major,o.minor]),t}),{});
return Object.values(o)},base64Encode:function(t){for(var o,e,n,a,c,i,s,l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",r="",u=0;
u<t.length;
)a=(o=t.charCodeAt(u++))>>2,c=(3&o)<<4|(e=t.charCodeAt(u++))>>4,i=(15&e)<<2|(n=t.charCodeAt(u++))>>6,s=63&n,isNaN(e)?i=s=64:isNaN(n)&&(s=64),r+=l.charAt(a)+l.charAt(c)+l.charAt(i)+l.charAt(s);
return r}});
