"use strict";
var t=require("../../@babel/runtime/helpers/createForOfIteratorHelper"),e=(getApp(),require("../../utils/util.js")),a=require("../../utils/watch.js"),o=require("../../service/dataService.js"),s=require("../../utils/schoolChange.js");
Page(e.merge({data:{layoutWidth:750,layoutHeight:350,libSelect:{id:0,title:"全部场馆"},libs:[],layout:[],layoutBar:[],proofs:[],choosedSeat:{},choosedSeatLength:0,choosedSeatSelected:{},num:"",talk:"",proofDialogTitle:"",showUserInfo:!1,userinfo:{},userinfoY:10},onReady:function(){console.log("onReady"),this.dialog=this.selectComponent("#dialog"),this.addNumDialog=this.selectComponent("#addNumDialog"),this.proofDialog=this.selectComponent("#proofDialog"),this.layout=this.selectComponent("#layout")},addProof:function(){var t=this;
this.data.proofs.length>=2?e.showError("最多能加2张图片"):wx.chooseImage({count:1,sizeType:["compressed"],sourceType:["camera"],success:function(a){console.log(a),t.urlTobase64(a.tempFilePaths[0]).then((function(s){o.uploadProof(s).then((function(o){0===o.code?(t.data.proofs.push({id:o.msg,src:a.tempFilePaths[0]}),console.log(t.data.proofs),t.setData({proofs:t.data.proofs})):e.showError(o.msg)}))})).catch((function(t){e.showError(t)}))}})},removeProof:function(t){var a=this,s=t.currentTarget.dataset.proof;
!s||s.id<=0?e.showError("证据获取失败"):wx.showModal({title:"确定删除该证据",content:"确定删除该证据?",success:function(t){t.confirm&&o.removeProof(s.id).then((function(t){if(0===t.code){var o=e.deleteArrayItemByCall(a.data.proofs,(function(t){return t.id=s.id}));
console.log("delete",o),a.setData({proofs:o})}else e.showError(t.msg)})).catch((function(t){e.showError(t)}))}})},urlTobase64:function(t){return new Promise((function(a,o){wx.getFileSystemManager().readFile({filePath:t,encoding:"base64",success:function(o){var s=wx.arrayBufferToBase64(o.data),i=e.ext(t);
s="data:image/".concat(i,";
base64,")+o.data,a(s)},fail:function(){o("获取图片数据错误")}})}))},hideProofDialog:function(){this.proofDialog.hideDialog()},watch:{choosedSeat:function(t){var e=this.getSeatsKeyArray(3).keys.length;
this.setData({choosedSeatLength:e})}},bindKeyInput:function(t){var e={};
e[t.target.id]=t.detail.value,this.setData(e)},libSelectHandler:function(t){var e=t.detail.value;
e.id!==this.data.libSelect.id&&(this.setData({libSelect:e,choosedSeat:{},choosedSeatSelected:{}}),this.layout.setColors({})),this.fetchApiData()},pageChangeHandler:function(t){this.addNumDialog.showDialog()},schChangeInPage:function(t){this.setData({libSelect:{id:0,title:"全部场馆"},choosedSeat:{},choosedSeatSelected:{}}),this.layout.setColors({}),this.fetchApiData()},seatClickHandler:function(t){var e=t.detail.seat,a=t.detail.event;
e.status&&this.chooseSeat(e,a)},hideUserInfo:function(t){this.setData({showUserInfo:!1})},refrashClickHandler:function(t){this.fetchApiData()},chooseNumHandler:function(t){var e=t.currentTarget.dataset.seat;
this.chooseNum(e)},chooseSeat:function(t,e){var a=this,s=this.data.choosedSeat,i=!1;
s[t.key]?delete s[t.key]:(s[t.key]=t,i=!0),this.setData({choosedSeat:s}),this.layout.setColors(s),i?this.data.libSelect&&this.data.libSelect.id&&o.seatUserInfo(this.data.libSelect.id,t.key).then((function(t){0===t.code&&(e.currentTarget.offsetTop,a.setData({userinfo:t.data,showUserInfo:!0}))})):this.setData({showUserInfo:!1})},chooseNum:function(t){var e=this.data.choosedSeatSelected;
e[t.key]?delete e[t.key]:e[t.key]=t,this.setData({choosedSeatSelected:e})},findSeat:function(t){var a=e.getStruct(this.data.layout,"seats");
if(a)for(var o in a)if(a[o].name&&a[o].name===t&&1==a[o].type&&a[o].status)return a[o];
return!1},getSeatsKeyArray:function(){var t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:null,e=this.data.choosedSeat,a=[],o=[];
for(var s in e)e.hasOwnProperty(s)&&(null===t||e[s].seat_status==t?a.push(s):o.push(e[s].name));
return{keys:a,unkeys:o}},addNumHandler:function(t){var a=this.data.num+"",o=this.findSeat(a);
if(!1===o)e.showError("未找到该座位号");
else{var s=this.data.choosedSeat;
a="",s[o.key]?this.setData({num:a}):(s[o.key]=o,this.setData({num:a,choosedSeat:s}),this.layout.setColors(s))}},delNumHandler:function(t){var e=this;
wx.showModal({title:"删除已选中的管理座位",content:"你确定删除已选中的管理座位?",success:function(t){if(t.confirm){var a=e.data.choosedSeatSelected,o=e.data.choosedSeat,s=!1;
for(var i in a)delete o[i],delete a[i],s=!0;
s&&(e.setData({choosedSeat:o,choosedSeatSelected:a}),e.layout.setColors(o))}}})},batMarkHandler:function(t){this.getSeatsKeyArray(3).keys.length<=0?e.showError("未能找到学习中的座位"):this.data.libSelect.id<=0?e.showError("当前场馆没有设置"):(this.setData({proofDialogTitle:"批量座位监督"}),this.proofDialog.showDialog())},batMarkSubmit:function(a){var s=this;
if(this.data.talk.length>25)e.showError("请填写小于25个汉字");
else{var i,r=this.getSeatsKeyArray(3),n=[],l=t(this.data.proofs);
try{for(l.s();
!(i=l.n()).done;
){var c=i.value;
n.push(c.id)}}catch(t){l.e(t)}finally{l.f()}var h="确认操作",d="你确定批量监督座位";
if(r.unkeys.length>0)h="发现选中的座位有的不是学习中的状态",d=r.unkeys.join(" ,")+" 的座位号的座位不是学习状态中的,点确定将仅对其他学习中的座位进行处理";
wx.showModal({title:h,content:d,success:function(t){if(t.confirm){o.batMark(s.data.libSelect.id,r.keys.join("|"),n.join(","),s.data.talk).then((function(t){0===t.code&&(s.setData({choosedSeat:{},choosedSeatSelected:{},talk:"",proofs:[]}),s.layout.setColors({}),s.proofDialog.hideDialog(),setTimeout((function(){s.fetchApiData()}),2e3)),e.showError(t.msg,2e3)}))}}})}},batFreeHandler:function(t){var a=this,s=this.getSeatsKeyArray();
s.keys.length<=0?e.showError("未能找到已预约的座位"):this.data.libSelect.id>0?wx.showModal({title:"确认操作",content:"你确定批量释放座位?",success:function(t){if(t.confirm){o.batFree(a.data.libSelect.id,s.keys.join("|")).then((function(t){0===t.code&&(a.setData({choosedSeat:{},choosedSeatSelected:{}}),a.layout.setColors({}),setTimeout((function(){a.fetchApiData()}),2e3)),e.showError(t.msg,2e3)}))}}}):e.showError("当前场馆没有设置")},fetchApiData:function(){var t=this,a=o.getCurrentSch({sch_id:0,name:"未设置"});
if(a.sch_id>0){console.log("free-request",a.sch_id);
var s=e.getStruct(this.data.libSelect,"id",0);
o.free(a.sch_id,s).then((function(a){if(console.log("free-result",a.data),0===a.code){var o=a.data.lib_layout;
t.data.libSelect.id<=0?t.setData({libs:a.data.libs,libSelect:a.data.libs[0]||{id:0,title:"全部场馆"},layout:o}):t.setData({libs:a.data.libs,layout:o})}else e.showError(a.msg);
return a}))}else e.showError("你没有设置当前学校")},onLoad:function(){a.setWatcher(this);
try{e.checkRedirect();
var t=o.getLayoutBar(),s=wx.getWindowInfo();
this.setData(e.merge({layoutWidth:s.windowWidth,layoutHeight:s.windowHeight-150-45,layoutBar:t},this.getCommonData())),this.fetchApiData()}catch(t){e.showError(t.message)}}},s));
