"use strict";
var t,e,r,i=require("../../@babel/runtime/helpers/typeof");
module.exports=(t={},r=function(e,r){if(!t[e])return require(r);
if(!t[e].status){var n=t[e].m;
n._exports=n._tempexports;
var s=Object.getOwnPropertyDescriptor(n,"exports");
s&&s.configurable&&Object.defineProperty(n,"exports",{set:function(t){"object"===i(t)&&t!==n._exports&&(n._exports.__proto__=t.__proto__,Object.keys(t).forEach((function(e){n._exports[e]=t[e]}))),n._tempexports=t},get:function(){return n._tempexports}}),t[e].status=1,t[e].func(t[e].req,n,n.exports)}return t[e].m.exports},(e=function(e,r,i){t[e]={status:0,func:r,req:i,m:{exports:{},_tempexports:{}}}})(1667461081096,(function(t,e,r){var i=t("./JSEncrypt").JSEncrypt;
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"JSEncrypt",{enumerable:!0,configurable:!0,get:function(){return i}}),r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.default=i}),(function(t){return r({"./JSEncrypt":1667461081097}[t],t)})),e(1667461081097,(function(t,e,r){var i,n=(h=t("./lib/jsbn/base64")).b64tohex,s=h.hex2b64,o=(h=t("./JSEncryptRSAKey")).JSEncryptRSAKey,h=t("./version.json"),u=(i=h)&&i.__esModule?i.default:i,a=function(){function t(t){void 0===t&&(t={}),t=t||{},this.default_key_size=t.default_key_size?parseInt(t.default_key_size,10):1024,this.default_public_exponent=t.default_public_exponent||"010001",this.log=t.log||!1,this.key=null}return t.prototype.setKey=function(t){this.log&&this.key&&console.warn("A key was already set, overriding existing."),this.key=new o(t)},t.prototype.setPrivateKey=function(t){this.setKey(t)},t.prototype.setPublicKey=function(t){this.setKey(t)},t.prototype.decrypt=function(t){try{return this.getKey().decrypt(n(t))}catch(t){return!1}},t.prototype.encrypt=function(t){try{return s(this.getKey().encrypt(t))}catch(t){return!1}},t.prototype.encryptLong=function(t){try{return s(this.getKey().encryptLong(t))}catch(t){return!1}},t.prototype.decryptLong=function(t){try{return this.getKey().decryptLong(n(t))}catch(t){return!1}},t.prototype.sign=function(t,e,r){try{return s(this.getKey().sign(t,e,r))}catch(t){return!1}},t.prototype.verify=function(t,e,r){try{return this.getKey().verify(t,n(e),r)}catch(t){return!1}},t.prototype.getKey=function(t){if(!this.key){if(this.key=new o,t&&"[object Function]"==={}.toString.call(t))return void this.key.generateAsync(this.default_key_size,this.default_public_exponent,t);
this.key.generate(this.default_key_size,this.default_public_exponent)}return this.key},t.prototype.getPrivateKey=function(){return this.getKey().getPrivateKey()},t.prototype.getPrivateKeyB64=function(){return this.getKey().getPrivateBaseKeyB64()},t.prototype.getPublicKey=function(){return this.getKey().getPublicKey()},t.prototype.getPublicKeyB64=function(){return this.getKey().getPublicBaseKeyB64()},t.version=u.version,t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"JSEncrypt",{enumerable:!0,configurable:!0,get:function(){return a}})}),(function(t){return r({"./lib/jsbn/base64":1667461081098,"./JSEncryptRSAKey":1667461081100,"./version.json":1667461081111}[t],t)})),e(1667461081098,(function(t,e,r){var i=t("./util").int2char,n="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
function s(t){var e,r="",s=0,o=0;
for(e=0;
e<t.length&&"="!=t.charAt(e);
++e){var h=n.indexOf(t.charAt(e));
h<0||(0==s?(r+=i(h>>2),o=3&h,s=1):1==s?(r+=i(o<<2|h>>4),o=15&h,s=2):2==s?(r+=i(o),r+=i(h>>2),o=3&h,s=3):(r+=i(o<<2|h>>4),r+=i(15&h),s=0))}return 1==s&&(r+=i(o<<2)),r}r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.hex2b64=function(t){var e,r,i="";
for(e=0;
e+3<=t.length;
e+=3)r=parseInt(t.substring(e,e+3),16),i+=n.charAt(r>>6)+n.charAt(63&r);
for(e+1==t.length?(r=parseInt(t.substring(e,e+1),16),i+=n.charAt(r<<2)):e+2==t.length&&(r=parseInt(t.substring(e,e+2),16),i+=n.charAt(r>>2)+n.charAt((3&r)<<4));
(3&i.length)>0;
)i+="=";
return i},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.b64tohex=s,r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.b64toBA=function(t){var e,r=s(t),i=[];
for(e=0;
2*e<r.length;
++e)i[e]=parseInt(r.substring(2*e,2*e+2),16);
return i}}),(function(t){return r({"./util":1667461081099}[t],t)})),e(1667461081099,(function(t,e,r){r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.int2char=function(t){return"0123456789abcdefghijklmnopqrstuvwxyz".charAt(t)},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.op_and=function(t,e){return t&e},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.op_or=function(t,e){return t|e},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.op_xor=function(t,e){return t^e},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.op_andnot=function(t,e){return t&~e},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.lbit=function(t){if(0==t)return-1;
var e=0;
return 0==(65535&t)&&(t>>=16,e+=16),0==(255&t)&&(t>>=8,e+=8),0==(15&t)&&(t>>=4,e+=4),0==(3&t)&&(t>>=2,e+=2),0==(1&t)&&++e,e},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.cbit=function(t){for(var e=0;
0!=t;
)t&=t-1,++e;
return e}}),(function(t){return r({}[t],t)})),e(1667461081100,(function(t,e,r){var i,n=this&&this.__extends||(i=function(t,e){return(i=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var r in e)Object.prototype.hasOwnProperty.call(e,r)&&(t[r]=e[r])})(t,e)},function(t,e){if("function"!=typeof e&&null!==e)throw new TypeError("Class extends value "+String(e)+" is not a constructor or null");
function r(){this.constructor=t}i(t,e),t.prototype=null===e?Object.create(e):(r.prototype=e.prototype,new r)}),s=t("./lib/jsbn/base64").hex2b64,o=t("./lib/asn1js/hex").Hex,h=t("./lib/asn1js/base64").Base64,u=t("./lib/asn1js/asn1").ASN1,a=t("./lib/jsbn/rsa").RSAKey,c=t("./lib/jsbn/jsbn").parseBigInt,f=t("./lib/jsrsasign/asn1-1.0").KJUR,l=function(t){function e(r){var i=t.call(this)||this;
return r&&("string"==typeof r?i.parseKey(r):(e.hasPrivateKeyProperty(r)||e.hasPublicKeyProperty(r))&&i.parsePropertiesFrom(r)),i}return n(e,t),e.prototype.parseKey=function(t){try{var e=0,r=0,i=/^\s*(?:[0-9A-Fa-f][0-9A-Fa-f]\s*)+$/.test(t)?o.decode(t):h.unarmor(t),n=u.decode(i);
if(3===n.sub.length&&(n=n.sub[2].sub[0]),9===n.sub.length){e=n.sub[1].getHexStringValue(),this.n=c(e,16),r=n.sub[2].getHexStringValue(),this.e=parseInt(r,16);
var s=n.sub[3].getHexStringValue();
this.d=c(s,16);
var a=n.sub[4].getHexStringValue();
this.p=c(a,16);
var f=n.sub[5].getHexStringValue();
this.q=c(f,16);
var l=n.sub[6].getHexStringValue();
this.dmp1=c(l,16);
var p=n.sub[7].getHexStringValue();
this.dmq1=c(p,16);
var g=n.sub[8].getHexStringValue();
this.coeff=c(g,16)}else{if(2!==n.sub.length)return!1;
var d=n.sub[1].sub[0];
e=d.sub[0].getHexStringValue(),this.n=c(e,16),r=d.sub[1].getHexStringValue(),this.e=parseInt(r,16)}return!0}catch(t){return!1}},e.prototype.getPrivateBaseKey=function(){var t={array:[new f.asn1.DERInteger({int:0}),new f.asn1.DERInteger({bigint:this.n}),new f.asn1.DERInteger({int:this.e}),new f.asn1.DERInteger({bigint:this.d}),new f.asn1.DERInteger({bigint:this.p}),new f.asn1.DERInteger({bigint:this.q}),new f.asn1.DERInteger({bigint:this.dmp1}),new f.asn1.DERInteger({bigint:this.dmq1}),new f.asn1.DERInteger({bigint:this.coeff})]};
return new f.asn1.DERSequence(t).getEncodedHex()},e.prototype.getPrivateBaseKeyB64=function(){return s(this.getPrivateBaseKey())},e.prototype.getPublicBaseKey=function(){var t=new f.asn1.DERSequence({array:[new f.asn1.DERObjectIdentifier({oid:"1.2.840.113549.1.1.1"}),new f.asn1.DERNull]}),e=new f.asn1.DERSequence({array:[new f.asn1.DERInteger({bigint:this.n}),new f.asn1.DERInteger({int:this.e})]}),r=new f.asn1.DERBitString({hex:"00"+e.getEncodedHex()});
return new f.asn1.DERSequence({array:[t,r]}).getEncodedHex()},e.prototype.getPublicBaseKeyB64=function(){return s(this.getPublicBaseKey())},e.wordwrap=function(t,e){if(!t)return t;
var r="(.{1,"+(e=e||64)+"})( +|$\n?)|(.{1,"+e+"})";
return t.match(RegExp(r,"g")).join("\n")},e.prototype.getPrivateKey=function(){var t="-----BEGIN RSA PRIVATE KEY-----\n";
return t+=e.wordwrap(this.getPrivateBaseKeyB64())+"\n",t+="-----END RSA PRIVATE KEY-----"},e.prototype.getPublicKey=function(){var t="-----BEGIN PUBLIC KEY-----\n";
return t+=e.wordwrap(this.getPublicBaseKeyB64())+"\n",t+="-----END PUBLIC KEY-----"},e.hasPublicKeyProperty=function(t){return(t=t||{}).hasOwnProperty("n")&&t.hasOwnProperty("e")},e.hasPrivateKeyProperty=function(t){return(t=t||{}).hasOwnProperty("n")&&t.hasOwnProperty("e")&&t.hasOwnProperty("d")&&t.hasOwnProperty("p")&&t.hasOwnProperty("q")&&t.hasOwnProperty("dmp1")&&t.hasOwnProperty("dmq1")&&t.hasOwnProperty("coeff")},e.prototype.parsePropertiesFrom=function(t){this.n=t.n,this.e=t.e,t.hasOwnProperty("d")&&(this.d=t.d,this.p=t.p,this.q=t.q,this.dmp1=t.dmp1,this.dmq1=t.dmq1,this.coeff=t.coeff)},e}(a);
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"JSEncryptRSAKey",{enumerable:!0,configurable:!0,get:function(){return l}})}),(function(t){return r({"./lib/jsbn/base64":1667461081098,"./lib/asn1js/hex":1667461081101,"./lib/asn1js/base64":1667461081102,"./lib/asn1js/asn1":1667461081103,"./lib/jsbn/rsa":1667461081105,"./lib/jsbn/jsbn":1667461081106,"./lib/jsrsasign/asn1-1.0":1667461081109}[t],t)})),e(1667461081101,(function(t,e,r){var i;
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.Hex={decode:function(t){var e;
if(void 0===i){var r="0123456789ABCDEF";
for(i={},e=0;
e<16;
++e)i[r.charAt(e)]=e;
for(r=r.toLowerCase(),e=10;
e<16;
++e)i[r.charAt(e)]=e;
for(e=0;
e<" \f\n\r\t \u2028\u2029".length;
++e)i[" \f\n\r\t \u2028\u2029".charAt(e)]=-1}var n=[],s=0,o=0;
for(e=0;
e<t.length;
++e){var h=t.charAt(e);
if("="==h)break;
if(-1!=(h=i[h])){if(void 0===h)throw new Error("Illegal character at offset "+e);
s|=h,++o>=2?(n[n.length]=s,s=0,o=0):s<<=4}}if(o)throw new Error("Hex encoding incomplete: 4 bits missing");
return n}}}),(function(t){return r({}[t],t)})),e(1667461081102,(function(t,e,r){var i;
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0});
var n=r.Base64={decode:function(t){var e;
if(void 0===i){for(i=Object.create(null),e=0;
e<64;
++e)i["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(e)]=e;
for(i["-"]=62,i._=63,e=0;
e<"= \f\n\r\t \u2028\u2029".length;
++e)i["= \f\n\r\t \u2028\u2029".charAt(e)]=-1}var r=[],n=0,s=0;
for(e=0;
e<t.length;
++e){var o=t.charAt(e);
if("="==o)break;
if(-1!=(o=i[o])){if(void 0===o)throw new Error("Illegal character at offset "+e);
n|=o,++s>=4?(r[r.length]=n>>16,r[r.length]=n>>8&255,r[r.length]=255&n,n=0,s=0):n<<=6}}switch(s){case 1:throw new Error("Base64 encoding incomplete: at least 2 bits missing");
case 2:r[r.length]=n>>10;
break;
case 3:r[r.length]=n>>16,r[r.length]=n>>8&255}return r},re:/-----BEGIN [^-]+-----([A-Za-z0-9+\/=\s]+)-----END [^-]+-----|begin-base64[^\n]+\n([A-Za-z0-9+\/=\s]+)====/,unarmor:function(t){var e=n.re.exec(t);
if(e)if(e[1])t=e[1];
else{if(!e[2])throw new Error("RegExp out of sync");
t=e[2]}return n.decode(t)}}}),(function(t){return r({}[t],t)})),e(1667461081103,(function(t,e,r){var i=t("./int10").Int10,n=/^(\d\d)(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([01]\d|2[0-3])(?:([0-5]\d)(?:([0-5]\d)(?:[.,](\d{1,3}))?)?)?(Z|[-+](?:[0]\d|1[0-2])([0-5]\d)?)?$/,s=/^(\d\d\d\d)(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])([01]\d|2[0-3])(?:([0-5]\d)(?:([0-5]\d)(?:[.,](\d{1,3}))?)?)?(Z|[-+](?:[0]\d|1[0-2])([0-5]\d)?)?$/;
function o(t,e){return t.length>e&&(t=t.substring(0,e)+"…"),t}var h=function(){function t(e,r){this.hexDigits="0123456789ABCDEF",e instanceof t?(this.enc=e.enc,this.pos=e.pos):(this.enc=e,this.pos=r)}return t.prototype.get=function(t){if(void 0===t&&(t=this.pos++),t>=this.enc.length)throw new Error("Requesting byte offset "+t+" on a stream of length "+this.enc.length);
return"string"==typeof this.enc?this.enc.charCodeAt(t):this.enc[t]},t.prototype.hexByte=function(t){return this.hexDigits.charAt(t>>4&15)+this.hexDigits.charAt(15&t)},t.prototype.hexDump=function(t,e,r){for(var i="",n=t;
n<e;
++n)if(i+=this.hexByte(this.get(n)),!0!==r)switch(15&n){case 7:i+="  ";
break;
case 15:i+="\n";
break;
default:i+=" "}return i},t.prototype.isASCII=function(t,e){for(var r=t;
r<e;
++r){var i=this.get(r);
if(i<32||i>176)return!1}return!0},t.prototype.parseStringISO=function(t,e){for(var r="",i=t;
i<e;
++i)r+=String.fromCharCode(this.get(i));
return r},t.prototype.parseStringUTF=function(t,e){for(var r="",i=t;
i<e;
){var n=this.get(i++);
r+=n<128?String.fromCharCode(n):n>191&&n<224?String.fromCharCode((31&n)<<6|63&this.get(i++)):String.fromCharCode((15&n)<<12|(63&this.get(i++))<<6|63&this.get(i++))}return r},t.prototype.parseStringBMP=function(t,e){for(var r,i,n="",s=t;
s<e;
)r=this.get(s++),i=this.get(s++),n+=String.fromCharCode(r<<8|i);
return n},t.prototype.parseTime=function(t,e,r){var i=this.parseStringISO(t,e),o=(r?n:s).exec(i);
return o?(r&&(o[1]=+o[1],o[1]+=+o[1]<70?2e3:1900),i=o[1]+"-"+o[2]+"-"+o[3]+" "+o[4],o[5]&&(i+=":"+o[5],o[6]&&(i+=":"+o[6],o[7]&&(i+="."+o[7]))),o[8]&&(i+=" UTC","Z"!=o[8]&&(i+=o[8],o[9]&&(i+=":"+o[9]))),i):"Unrecognized time: "+i},t.prototype.parseInteger=function(t,e){for(var r,n=this.get(t),s=n>127,o=s?255:0,h="";
n==o&&++t<e;
)n=this.get(t);
if(0==(r=e-t))return s?-1:0;
if(r>4){for(h=n,r<<=3;
0==(128&(+h^o));
)h=+h<<1,--r;
h="("+r+" bit)\n"}s&&(n-=256);
for(var u=new i(n),a=t+1;
a<e;
++a)u.mulAdd(256,this.get(a));
return h+u.toString()},t.prototype.parseBitString=function(t,e,r){for(var i=this.get(t),n="("+((e-t-1<<3)-i)+" bit)\n",s="",h=t+1;
h<e;
++h){for(var u=this.get(h),a=h==e-1?i:0,c=7;
c>=a;
--c)s+=u>>c&1?"1":"0";
if(s.length>r)return n+o(s,r)}return n+s},t.prototype.parseOctetString=function(t,e,r){if(this.isASCII(t,e))return o(this.parseStringISO(t,e),r);
var i=e-t,n="("+i+" byte)\n";
i>(r/=2)&&(e=t+r);
for(var s=t;
s<e;
++s)n+=this.hexByte(this.get(s));
return i>r&&(n+="…"),n},t.prototype.parseOID=function(t,e,r){for(var n="",s=new i,h=0,u=t;
u<e;
++u){var a=this.get(u);
if(s.mulAdd(128,127&a),h+=7,!(128&a)){if(""===n)if((s=s.simplify())instanceof i)s.sub(80),n="2."+s.toString();
else{var c=s<80?s<40?0:1:2;
n=c+"."+(s-40*c)}else n+="."+s.toString();
if(n.length>r)return o(n,r);
s=new i,h=0}}return h>0&&(n+=".incomplete"),n},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"Stream",{enumerable:!0,configurable:!0,get:function(){return h}});
var u=function(){function t(t,e,r,i,n){if(!(i instanceof a))throw new Error("Invalid tag value.");
this.stream=t,this.header=e,this.length=r,this.tag=i,this.sub=n}return t.prototype.typeName=function(){switch(this.tag.tagClass){case 0:switch(this.tag.tagNumber){case 0:return"EOC";
case 1:return"BOOLEAN";
case 2:return"INTEGER";
case 3:return"BIT_STRING";
case 4:return"OCTET_STRING";
case 5:return"NULL";
case 6:return"OBJECT_IDENTIFIER";
case 7:return"ObjectDescriptor";
case 8:return"EXTERNAL";
case 9:return"REAL";
case 10:return"ENUMERATED";
case 11:return"EMBEDDED_PDV";
case 12:return"UTF8String";
case 16:return"SEQUENCE";
case 17:return"SET";
case 18:return"NumericString";
case 19:return"PrintableString";
case 20:return"TeletexString";
case 21:return"VideotexString";
case 22:return"IA5String";
case 23:return"UTCTime";
case 24:return"GeneralizedTime";
case 25:return"GraphicString";
case 26:return"VisibleString";
case 27:return"GeneralString";
case 28:return"UniversalString";
case 30:return"BMPString"}return"Universal_"+this.tag.tagNumber.toString();
case 1:return"Application_"+this.tag.tagNumber.toString();
case 2:return"["+this.tag.tagNumber.toString()+"]";
case 3:return"Private_"+this.tag.tagNumber.toString()}},t.prototype.content=function(t){if(void 0===this.tag)return null;
void 0===t&&(t=1/0);
var e=this.posContent(),r=Math.abs(this.length);
if(!this.tag.isUniversal())return null!==this.sub?"("+this.sub.length+" elem)":this.stream.parseOctetString(e,e+r,t);
switch(this.tag.tagNumber){case 1:return 0===this.stream.get(e)?"false":"true";
case 2:return this.stream.parseInteger(e,e+r);
case 3:return this.sub?"("+this.sub.length+" elem)":this.stream.parseBitString(e,e+r,t);
case 4:return this.sub?"("+this.sub.length+" elem)":this.stream.parseOctetString(e,e+r,t);
case 6:return this.stream.parseOID(e,e+r,t);
case 16:case 17:return null!==this.sub?"("+this.sub.length+" elem)":"(no elem)";
case 12:return o(this.stream.parseStringUTF(e,e+r),t);
case 18:case 19:case 20:case 21:case 22:case 26:return o(this.stream.parseStringISO(e,e+r),t);
case 30:return o(this.stream.parseStringBMP(e,e+r),t);
case 23:case 24:return this.stream.parseTime(e,e+r,23==this.tag.tagNumber)}return null},t.prototype.toString=function(){return this.typeName()+"@"+this.stream.pos+"[header:"+this.header+",length:"+this.length+",sub:"+(null===this.sub?"null":this.sub.length)+"]"},t.prototype.toPrettyString=function(t){void 0===t&&(t="");
var e=t+this.typeName()+" @"+this.stream.pos;
if(this.length>=0&&(e+="+"),e+=this.length,this.tag.tagConstructed?e+=" (constructed)":!this.tag.isUniversal()||3!=this.tag.tagNumber&&4!=this.tag.tagNumber||null===this.sub||(e+=" (encapsulates)"),e+="\n",null!==this.sub){t+="  ";
for(var r=0,i=this.sub.length;
r<i;
++r)e+=this.sub[r].toPrettyString(t)}return e},t.prototype.posStart=function(){return this.stream.pos},t.prototype.posContent=function(){return this.stream.pos+this.header},t.prototype.posEnd=function(){return this.stream.pos+this.header+Math.abs(this.length)},t.prototype.toHexString=function(){return this.stream.hexDump(this.posStart(),this.posEnd(),!0)},t.decodeLength=function(t){var e=t.get(),r=127&e;
if(r==e)return r;
if(r>6)throw new Error("Length over 48 bits not supported at position "+(t.pos-1));
if(0===r)return null;
e=0;
for(var i=0;
i<r;
++i)e=256*e+t.get();
return e},t.prototype.getHexStringValue=function(){var t=this.toHexString(),e=2*this.header,r=2*this.length;
return t.substr(e,r)},t.decode=function(e){var r;
r=e instanceof h?e:new h(e,0);
var i=new h(r),n=new a(r),s=t.decodeLength(r),o=r.pos,u=o-i.pos,c=null,f=function(){var e=[];
if(null!==s){for(var i=o+s;
r.pos<i;
)e[e.length]=t.decode(r);
if(r.pos!=i)throw new Error("Content size is not correct for container starting at offset "+o)}else try{for(;
;
){var n=t.decode(r);
if(n.tag.isEOC())break;
e[e.length]=n}s=o-r.pos}catch(t){throw new Error("Exception while decoding undefined length content: "+t)}return e};
if(n.tagConstructed)c=f();
else if(n.isUniversal()&&(3==n.tagNumber||4==n.tagNumber))try{if(3==n.tagNumber&&0!=r.get())throw new Error("BIT STRINGs with unused bits cannot encapsulate.");
c=f();
for(var l=0;
l<c.length;
++l)if(c[l].tag.isEOC())throw new Error("EOC is not supposed to be actual content.")}catch(t){c=null}if(null===c){if(null===s)throw new Error("We can't skip over an invalid tag with undefined length at offset "+o);
r.pos=o+Math.abs(s)}return new t(i,u,s,n,c)},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"ASN1",{enumerable:!0,configurable:!0,get:function(){return u}});
var a=function(){function t(t){var e=t.get();
if(this.tagClass=e>>6,this.tagConstructed=0!=(32&e),this.tagNumber=31&e,31==this.tagNumber){var r=new i;
do{e=t.get(),r.mulAdd(128,127&e)}while(128&e);
this.tagNumber=r.simplify()}}return t.prototype.isUniversal=function(){return 0===this.tagClass},t.prototype.isEOC=function(){return 0===this.tagClass&&0===this.tagNumber},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"ASN1Tag",{enumerable:!0,configurable:!0,get:function(){return a}})}),(function(t){return r({"./int10":1667461081104}[t],t)})),e(1667461081104,(function(t,e,r){var i=1e13,n=function(){function t(t){this.buf=[+t||0]}return t.prototype.mulAdd=function(t,e){var r,n,s=this.buf,o=s.length;
for(r=0;
r<o;
++r)(n=s[r]*t+e)<i?e=0:n-=(e=0|n/i)*i,s[r]=n;
e>0&&(s[r]=e)},t.prototype.sub=function(t){var e,r,n=this.buf,s=n.length;
for(e=0;
e<s;
++e)(r=n[e]-t)<0?(r+=i,t=1):t=0,n[e]=r;
for(;
0===n[n.length-1];
)n.pop()},t.prototype.toString=function(t){if(10!=(t||10))throw new Error("only base 10 is supported");
for(var e=this.buf,r=e[e.length-1].toString(),n=e.length-2;
n>=0;
--n)r+=(i+e[n]).toString().substring(1);
return r},t.prototype.valueOf=function(){for(var t=this.buf,e=0,r=t.length-1;
r>=0;
--r)e=e*i+t[r];
return e},t.prototype.simplify=function(){var t=this.buf;
return 1==t.length?t[0]:this},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"Int10",{enumerable:!0,configurable:!0,get:function(){return n}})}),(function(t){return r({}[t],t)})),e(1667461081105,(function(t,e,r){var i,n=(i=t("./jsbn")).BigInteger,s=i.nbi,o=i.parseBigInt,h=(i=t("./rng")).SecureRandom,u=function(){function t(){this.n=null,this.e=0,this.d=null,this.p=null,this.q=null,this.dmp1=null,this.dmq1=null,this.coeff=null}return t.prototype.doPublic=function(t){return t.modPowInt(this.e,this.n)},t.prototype.doPrivate=function(t){if(null==this.p||null==this.q)return t.modPow(this.d,this.n);
for(var e=t.mod(this.p).modPow(this.dmp1,this.p),r=t.mod(this.q).modPow(this.dmq1,this.q);
e.compareTo(r)<0;
)e=e.add(this.p);
return e.subtract(r).multiply(this.coeff).mod(this.p).multiply(this.q).add(r)},t.prototype.setPublic=function(t,e){null!=t&&null!=e&&t.length>0&&e.length>0?(this.n=o(t,16),this.e=parseInt(e,16)):console.error("Invalid RSA public key")},t.prototype.encrypt=function(t){var e=this.n.bitLength()+7>>3,r=function(t,e){if(e<t.length+11)return console.error("Message too long for RSA"),null;
for(var r=[],i=t.length-1;
i>=0&&e>0;
){var s=t.charCodeAt(i--);
s<128?r[--e]=s:s>127&&s<2048?(r[--e]=63&s|128,r[--e]=s>>6|192):(r[--e]=63&s|128,r[--e]=s>>6&63|128,r[--e]=s>>12|224)}r[--e]=0;
for(var o=new h,u=[];
e>2;
){for(u[0]=0;
0==u[0];
)o.nextBytes(u);
r[--e]=u[0]}return r[--e]=2,r[--e]=0,new n(r)}(t,e);
if(null==r)return null;
var i=this.doPublic(r);
if(null==i)return null;
for(var s=i.toString(16),o=s.length,u=0;
u<2*e-o;
u++)s="0"+s;
return s},t.prototype.setPrivate=function(t,e,r){null!=t&&null!=e&&t.length>0&&e.length>0?(this.n=o(t,16),this.e=parseInt(e,16),this.d=o(r,16)):console.error("Invalid RSA private key")},t.prototype.setPrivateEx=function(t,e,r,i,n,s,h,u){null!=t&&null!=e&&t.length>0&&e.length>0?(this.n=o(t,16),this.e=parseInt(e,16),this.d=o(r,16),this.p=o(i,16),this.q=o(n,16),this.dmp1=o(s,16),this.dmq1=o(h,16),this.coeff=o(u,16)):console.error("Invalid RSA private key")},t.prototype.generate=function(t,e){var r=new h,i=t>>1;
this.e=parseInt(e,16);
for(var s=new n(e,16);
;
){for(;
this.p=new n(t-i,1,r),0!=this.p.subtract(n.ONE).gcd(s).compareTo(n.ONE)||!this.p.isProbablePrime(10);
);
for(;
this.q=new n(i,1,r),0!=this.q.subtract(n.ONE).gcd(s).compareTo(n.ONE)||!this.q.isProbablePrime(10);
);
if(this.p.compareTo(this.q)<=0){var o=this.p;
this.p=this.q,this.q=o}var u=this.p.subtract(n.ONE),a=this.q.subtract(n.ONE),c=u.multiply(a);
if(0==c.gcd(s).compareTo(n.ONE)){this.n=this.p.multiply(this.q),this.d=s.modInverse(c),this.dmp1=this.d.mod(u),this.dmq1=this.d.mod(a),this.coeff=this.q.modInverse(this.p);
break}}},t.prototype.decrypt=function(t){var e=o(t,16),r=this.doPrivate(e);
return null==r?null:function(t,e){for(var r=t.toByteArray(),i=0;
i<r.length&&0==r[i];
)++i;
if(r.length-i!=e-1||2!=r[i])return null;
for(++i;
0!=r[i];
)if(++i>=r.length)return null;
for(var n="";
++i<r.length;
){var s=255&r[i];
s<128?n+=String.fromCharCode(s):s>191&&s<224?(n+=String.fromCharCode((31&s)<<6|63&r[i+1]),++i):(n+=String.fromCharCode((15&s)<<12|(63&r[i+1])<<6|63&r[i+2]),i+=2)}return n}(r,this.n.bitLength()+7>>3)},t.prototype.generateAsync=function(t,e,r){var i=new h,o=t>>1;
this.e=parseInt(e,16);
var u=new n(e,16),a=this,c=function(){var e=function(){if(a.p.compareTo(a.q)<=0){var t=a.p;
a.p=a.q,a.q=t}var e=a.p.subtract(n.ONE),i=a.q.subtract(n.ONE),s=e.multiply(i);
0==s.gcd(u).compareTo(n.ONE)?(a.n=a.p.multiply(a.q),a.d=u.modInverse(s),a.dmp1=a.d.mod(e),a.dmq1=a.d.mod(i),a.coeff=a.q.modInverse(a.p),setTimeout((function(){r()}),0)):setTimeout(c,0)},h=function(){a.q=s(),a.q.fromNumberAsync(o,1,i,(function(){a.q.subtract(n.ONE).gcda(u,(function(t){0==t.compareTo(n.ONE)&&a.q.isProbablePrime(10)?setTimeout(e,0):setTimeout(h,0)}))}))},f=function(){a.p=s(),a.p.fromNumberAsync(t-o,1,i,(function(){a.p.subtract(n.ONE).gcda(u,(function(t){0==t.compareTo(n.ONE)&&a.p.isProbablePrime(10)?setTimeout(h,0):setTimeout(f,0)}))}))};
setTimeout(f,0)};
setTimeout(c,0)},t.prototype.sign=function(t,e,r){var i=function(t,e){if(e<t.length+22)return console.error("Message too long for RSA"),null;
for(var r=e-t.length-6,i="",n=0;
n<r;
n+=2)i+="ff";
return o("0001"+i+"00"+t,16)}((a[r]||"")+e(t).toString(),this.n.bitLength()/4);
if(null==i)return null;
var n=this.doPrivate(i);
if(null==n)return null;
var s=n.toString(16);
return 0==(1&s.length)?s:"0"+s},t.prototype.verify=function(t,e,r){var i=o(e,16),n=this.doPublic(i);
return null==n?null:function(t){for(var e in a)if(a.hasOwnProperty(e)){var r=a[e],i=r.length;
if(t.substr(0,i)==r)return t.substr(i)}return t}(n.toString(16).replace(/^1f+00/,""))==r(t).toString()},t.prototype.encryptLong=function(t){var e=this,r="",i=(this.n.bitLength()+7>>3)-11;
return this.setSplitChn(t,i).forEach((function(t){r+=e.encrypt(t)})),r},t.prototype.decryptLong=function(t){var e="",r=this.n.bitLength()+7>>3,i=2*r;
if(t.length>i){for(var n=t.match(new RegExp(".{1,"+i+"}","g"))||[],s=[],h=0;
h<n.length;
h++){var u=o(n[h],16),a=this.doPrivate(u);
if(null==a)return null;
s.push(a)}e=function(t,e){for(var r=[],i=0;
i<t.length;
i++){for(var n=t[i].toByteArray(),s=0;
s<n.length&&0==n[s];
)++s;
if(n.length-s!=e-1||2!=n[s])return null;
for(++s;
0!=n[s];
)if(++s>=n.length)return null;
r=r.concat(n.slice(s+1))}for(var o=r,h=-1,u="";
++h<o.length;
){var a=255&o[h];
a<128?u+=String.fromCharCode(a):a>191&&a<224?(u+=String.fromCharCode((31&a)<<6|63&o[h+1]),++h):(u+=String.fromCharCode((15&a)<<12|(63&o[h+1])<<6|63&o[h+2]),h+=2)}return u}(s,r)}else e=this.decrypt(t);
return e},t.prototype.setSplitChn=function(t,e,r){void 0===r&&(r=[]);
for(var i=t.split(""),n=0,s=0;
s<i.length;
s++){var o=i[s].charCodeAt(0);
if((n+=o<=127?1:o<=2047?2:o<=65535?3:4)>e){var h=t.substring(0,s);
return r.push(h),this.setSplitChn(t.substring(s),e,r)}}return r.push(t),r},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"RSAKey",{enumerable:!0,configurable:!0,get:function(){return u}});
var a={md2:"3020300c06082a864886f70d020205000410",md5:"3020300c06082a864886f70d020505000410",sha1:"3021300906052b0e03021a05000414",sha224:"302d300d06096086480165030402040500041c",sha256:"3031300d060960864801650304020105000420",sha384:"3041300d060960864801650304020205000430",sha512:"3051300d060960864801650304020305000440",ripemd160:"3021300906052b2403020105000414"}}),(function(t){return r({"./jsbn":1667461081106,"./rng":1667461081107}[t],t)})),e(1667461081106,(function(t,e,r){var i,n=t("./util"),s=n.cbit,o=n.int2char,h=n.lbit,u=n.op_and,a=n.op_andnot,c=n.op_or,f=n.op_xor,l=[2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,67,71,73,79,83,89,97,101,103,107,109,113,127,131,137,139,149,151,157,163,167,173,179,181,191,193,197,199,211,223,227,229,233,239,241,251,257,263,269,271,277,281,283,293,307,311,313,317,331,337,347,349,353,359,367,373,379,383,389,397,401,409,419,421,431,433,439,443,449,457,461,463,467,479,487,491,499,503,509,521,523,541,547,557,563,569,571,577,587,593,599,601,607,613,617,619,631,641,643,647,653,659,661,673,677,683,691,701,709,719,727,733,739,743,751,757,761,769,773,787,797,809,811,821,823,827,829,839,853,857,859,863,877,881,883,887,907,911,919,929,937,941,947,953,967,971,977,983,991,997],p=(1<<26)/l[l.length-1],g=function(){function t(t,e,r){null!=t&&("number"==typeof t?this.fromNumber(t,e,r):null==e&&"string"!=typeof t?this.fromString(t,256):this.fromString(t,e))}return t.prototype.toString=function(t){if(this.s<0)return"-"+this.negate().toString(t);
var e;
if(16==t)e=4;
else if(8==t)e=3;
else if(2==t)e=1;
else if(32==t)e=5;
else{if(4!=t)return this.toRadix(t);
e=2}var r,i=(1<<e)-1,n=!1,s="",h=this.t,u=this.DB-h*this.DB%e;
if(h-- >0)for(u<this.DB&&(r=this[h]>>u)>0&&(n=!0,s=o(r));
h>=0;
)u<e?(r=(this[h]&(1<<u)-1)<<e-u,r|=this[--h]>>(u+=this.DB-e)):(r=this[h]>>(u-=e)&i,u<=0&&(u+=this.DB,--h)),r>0&&(n=!0),n&&(s+=o(r));
return n?s:"0"},t.prototype.negate=function(){var e=m();
return t.ZERO.subTo(this,e),e},t.prototype.abs=function(){return this.s<0?this.negate():this},t.prototype.compareTo=function(t){var e=this.s-t.s;
if(0!=e)return e;
var r=this.t;
if(0!=(e=r-t.t))return this.s<0?-e:e;
for(;
--r>=0;
)if(0!=(e=this[r]-t[r]))return e;
return 0},t.prototype.bitLength=function(){return this.t<=0?0:this.DB*(this.t-1)+_(this[this.t-1]^this.s&this.DM)},t.prototype.mod=function(e){var r=m();
return this.abs().divRemTo(e,null,r),this.s<0&&r.compareTo(t.ZERO)>0&&e.subTo(r,r),r},t.prototype.modPowInt=function(t,e){var r;
return r=t<256||e.isEven()?new y(e):new v(e),this.exp(t,r)},t.prototype.clone=function(){var t=m();
return this.copyTo(t),t},t.prototype.intValue=function(){if(this.s<0){if(1==this.t)return this[0]-this.DV;
if(0==this.t)return-1}else{if(1==this.t)return this[0];
if(0==this.t)return 0}return(this[1]&(1<<32-this.DB)-1)<<this.DB|this[0]},t.prototype.byteValue=function(){return 0==this.t?this.s:this[0]<<24>>24},t.prototype.shortValue=function(){return 0==this.t?this.s:this[0]<<16>>16},t.prototype.signum=function(){return this.s<0?-1:this.t<=0||1==this.t&&this[0]<=0?0:1},t.prototype.toByteArray=function(){var t=this.t,e=[];
e[0]=this.s;
var r,i=this.DB-t*this.DB%8,n=0;
if(t-- >0)for(i<this.DB&&(r=this[t]>>i)!=(this.s&this.DM)>>i&&(e[n++]=r|this.s<<this.DB-i);
t>=0;
)i<8?(r=(this[t]&(1<<i)-1)<<8-i,r|=this[--t]>>(i+=this.DB-8)):(r=this[t]>>(i-=8)&255,i<=0&&(i+=this.DB,--t)),0!=(128&r)&&(r|=-256),0==n&&(128&this.s)!=(128&r)&&++n,(n>0||r!=this.s)&&(e[n++]=r);
return e},t.prototype.equals=function(t){return 0==this.compareTo(t)},t.prototype.min=function(t){return this.compareTo(t)<0?this:t},t.prototype.max=function(t){return this.compareTo(t)>0?this:t},t.prototype.and=function(t){var e=m();
return this.bitwiseTo(t,u,e),e},t.prototype.or=function(t){var e=m();
return this.bitwiseTo(t,c,e),e},t.prototype.xor=function(t){var e=m();
return this.bitwiseTo(t,f,e),e},t.prototype.andNot=function(t){var e=m();
return this.bitwiseTo(t,a,e),e},t.prototype.not=function(){for(var t=m(),e=0;
e<this.t;
++e)t[e]=this.DM&~this[e];
return t.t=this.t,t.s=~this.s,t},t.prototype.shiftLeft=function(t){var e=m();
return t<0?this.rShiftTo(-t,e):this.lShiftTo(t,e),e},t.prototype.shiftRight=function(t){var e=m();
return t<0?this.lShiftTo(-t,e):this.rShiftTo(t,e),e},t.prototype.getLowestSetBit=function(){for(var t=0;
t<this.t;
++t)if(0!=this[t])return t*this.DB+h(this[t]);
return this.s<0?this.t*this.DB:-1},t.prototype.bitCount=function(){for(var t=0,e=this.s&this.DM,r=0;
r<this.t;
++r)t+=s(this[r]^e);
return t},t.prototype.testBit=function(t){var e=Math.floor(t/this.DB);
return e>=this.t?0!=this.s:0!=(this[e]&1<<t%this.DB)},t.prototype.setBit=function(t){return this.changeBit(t,c)},t.prototype.clearBit=function(t){return this.changeBit(t,a)},t.prototype.flipBit=function(t){return this.changeBit(t,f)},t.prototype.add=function(t){var e=m();
return this.addTo(t,e),e},t.prototype.subtract=function(t){var e=m();
return this.subTo(t,e),e},t.prototype.multiply=function(t){var e=m();
return this.multiplyTo(t,e),e},t.prototype.divide=function(t){var e=m();
return this.divRemTo(t,e,null),e},t.prototype.remainder=function(t){var e=m();
return this.divRemTo(t,null,e),e},t.prototype.divideAndRemainder=function(t){var e=m(),r=m();
return this.divRemTo(t,e,r),[e,r]},t.prototype.modPow=function(t,e){var r,i,n=t.bitLength(),s=x(1);
if(n<=0)return s;
r=n<18?1:n<48?3:n<144?4:n<768?5:6,i=n<8?new y(e):e.isEven()?new b(e):new v(e);
var o=[],h=3,u=r-1,a=(1<<r)-1;
if(o[1]=i.convert(this),r>1){var c=m();
for(i.sqrTo(o[1],c);
h<=a;
)o[h]=m(),i.mulTo(c,o[h-2],o[h]),h+=2}var f,l,p=t.t-1,g=!0,d=m();
for(n=_(t[p])-1;
p>=0;
){for(n>=u?f=t[p]>>n-u&a:(f=(t[p]&(1<<n+1)-1)<<u-n,p>0&&(f|=t[p-1]>>this.DB+n-u)),h=r;
0==(1&f);
)f>>=1,--h;
if((n-=h)<0&&(n+=this.DB,--p),g)o[f].copyTo(s),g=!1;
else{for(;
h>1;
)i.sqrTo(s,d),i.sqrTo(d,s),h-=2;
h>0?i.sqrTo(s,d):(l=s,s=d,d=l),i.mulTo(d,o[f],s)}for(;
p>=0&&0==(t[p]&1<<n);
)i.sqrTo(s,d),l=s,s=d,d=l,--n<0&&(n=this.DB-1,--p)}return i.revert(s)},t.prototype.modInverse=function(e){var r=e.isEven();
if(this.isEven()&&r||0==e.signum())return t.ZERO;
for(var i=e.clone(),n=this.clone(),s=x(1),o=x(0),h=x(0),u=x(1);
0!=i.signum();
){for(;
i.isEven();
)i.rShiftTo(1,i),r?(s.isEven()&&o.isEven()||(s.addTo(this,s),o.subTo(e,o)),s.rShiftTo(1,s)):o.isEven()||o.subTo(e,o),o.rShiftTo(1,o);
for(;
n.isEven();
)n.rShiftTo(1,n),r?(h.isEven()&&u.isEven()||(h.addTo(this,h),u.subTo(e,u)),h.rShiftTo(1,h)):u.isEven()||u.subTo(e,u),u.rShiftTo(1,u);
i.compareTo(n)>=0?(i.subTo(n,i),r&&s.subTo(h,s),o.subTo(u,o)):(n.subTo(i,n),r&&h.subTo(s,h),u.subTo(o,u))}return 0!=n.compareTo(t.ONE)?t.ZERO:u.compareTo(e)>=0?u.subtract(e):u.signum()<0?(u.addTo(e,u),u.signum()<0?u.add(e):u):u},t.prototype.pow=function(t){return this.exp(t,new d)},t.prototype.gcd=function(t){var e=this.s<0?this.negate():this.clone(),r=t.s<0?t.negate():t.clone();
if(e.compareTo(r)<0){var i=e;
e=r,r=i}var n=e.getLowestSetBit(),s=r.getLowestSetBit();
if(s<0)return e;
for(n<s&&(s=n),s>0&&(e.rShiftTo(s,e),r.rShiftTo(s,r));
e.signum()>0;
)(n=e.getLowestSetBit())>0&&e.rShiftTo(n,e),(n=r.getLowestSetBit())>0&&r.rShiftTo(n,r),e.compareTo(r)>=0?(e.subTo(r,e),e.rShiftTo(1,e)):(r.subTo(e,r),r.rShiftTo(1,r));
return s>0&&r.lShiftTo(s,r),r},t.prototype.isProbablePrime=function(t){var e,r=this.abs();
if(1==r.t&&r[0]<=l[l.length-1]){for(e=0;
e<l.length;
++e)if(r[0]==l[e])return!0;
return!1}if(r.isEven())return!1;
for(e=1;
e<l.length;
){for(var i=l[e],n=e+1;
n<l.length&&i<p;
)i*=l[n++];
for(i=r.modInt(i);
e<n;
)if(i%l[e++]==0)return!1}return r.millerRabin(t)},t.prototype.copyTo=function(t){for(var e=this.t-1;
e>=0;
--e)t[e]=this[e];
t.t=this.t,t.s=this.s},t.prototype.fromInt=function(t){this.t=1,this.s=t<0?-1:0,t>0?this[0]=t:t<-1?this[0]=t+this.DV:this.t=0},t.prototype.fromString=function(e,r){var i;
if(16==r)i=4;
else if(8==r)i=3;
else if(256==r)i=8;
else if(2==r)i=1;
else if(32==r)i=5;
else{if(4!=r)return void this.fromRadix(e,r);
i=2}this.t=0,this.s=0;
for(var n=e.length,s=!1,o=0;
--n>=0;
){var h=8==i?255&+e[n]:w(e,n);
h<0?"-"==e.charAt(n)&&(s=!0):(s=!1,0==o?this[this.t++]=h:o+i>this.DB?(this[this.t-1]|=(h&(1<<this.DB-o)-1)<<o,this[this.t++]=h>>this.DB-o):this[this.t-1]|=h<<o,(o+=i)>=this.DB&&(o-=this.DB))}8==i&&0!=(128&+e[0])&&(this.s=-1,o>0&&(this[this.t-1]|=(1<<this.DB-o)-1<<o)),this.clamp(),s&&t.ZERO.subTo(this,this)},t.prototype.clamp=function(){for(var t=this.s&this.DM;
this.t>0&&this[this.t-1]==t;
)--this.t},t.prototype.dlShiftTo=function(t,e){var r;
for(r=this.t-1;
r>=0;
--r)e[r+t]=this[r];
for(r=t-1;
r>=0;
--r)e[r]=0;
e.t=this.t+t,e.s=this.s},t.prototype.drShiftTo=function(t,e){for(var r=t;
r<this.t;
++r)e[r-t]=this[r];
e.t=Math.max(this.t-t,0),e.s=this.s},t.prototype.lShiftTo=function(t,e){for(var r=t%this.DB,i=this.DB-r,n=(1<<i)-1,s=Math.floor(t/this.DB),o=this.s<<r&this.DM,h=this.t-1;
h>=0;
--h)e[h+s+1]=this[h]>>i|o,o=(this[h]&n)<<r;
for(h=s-1;
h>=0;
--h)e[h]=0;
e[s]=o,e.t=this.t+s+1,e.s=this.s,e.clamp()},t.prototype.rShiftTo=function(t,e){e.s=this.s;
var r=Math.floor(t/this.DB);
if(r>=this.t)e.t=0;
else{var i=t%this.DB,n=this.DB-i,s=(1<<i)-1;
e[0]=this[r]>>i;
for(var o=r+1;
o<this.t;
++o)e[o-r-1]|=(this[o]&s)<<n,e[o-r]=this[o]>>i;
i>0&&(e[this.t-r-1]|=(this.s&s)<<n),e.t=this.t-r,e.clamp()}},t.prototype.subTo=function(t,e){for(var r=0,i=0,n=Math.min(t.t,this.t);
r<n;
)i+=this[r]-t[r],e[r++]=i&this.DM,i>>=this.DB;
if(t.t<this.t){for(i-=t.s;
r<this.t;
)i+=this[r],e[r++]=i&this.DM,i>>=this.DB;
i+=this.s}else{for(i+=this.s;
r<t.t;
)i-=t[r],e[r++]=i&this.DM,i>>=this.DB;
i-=t.s}e.s=i<0?-1:0,i<-1?e[r++]=this.DV+i:i>0&&(e[r++]=i),e.t=r,e.clamp()},t.prototype.multiplyTo=function(e,r){var i=this.abs(),n=e.abs(),s=i.t;
for(r.t=s+n.t;
--s>=0;
)r[s]=0;
for(s=0;
s<n.t;
++s)r[s+i.t]=i.am(0,n[s],r,s,0,i.t);
r.s=0,r.clamp(),this.s!=e.s&&t.ZERO.subTo(r,r)},t.prototype.squareTo=function(t){for(var e=this.abs(),r=t.t=2*e.t;
--r>=0;
)t[r]=0;
for(r=0;
r<e.t-1;
++r){var i=e.am(r,e[r],t,2*r,0,1);
(t[r+e.t]+=e.am(r+1,2*e[r],t,2*r+1,i,e.t-r-1))>=e.DV&&(t[r+e.t]-=e.DV,t[r+e.t+1]=1)}t.t>0&&(t[t.t-1]+=e.am(r,e[r],t,2*r,0,1)),t.s=0,t.clamp()},t.prototype.divRemTo=function(e,r,i){var n=e.abs();
if(!(n.t<=0)){var s=this.abs();
if(s.t<n.t)return null!=r&&r.fromInt(0),void(null!=i&&this.copyTo(i));
null==i&&(i=m());
var o=m(),h=this.s,u=e.s,a=this.DB-_(n[n.t-1]);
a>0?(n.lShiftTo(a,o),s.lShiftTo(a,i)):(n.copyTo(o),s.copyTo(i));
var c=o.t,f=o[c-1];
if(0!=f){var l=f*(1<<this.F1)+(c>1?o[c-2]>>this.F2:0),p=this.FV/l,g=(1<<this.F1)/l,d=1<<this.F2,y=i.t,v=y-c,b=null==r?m():r;
for(o.dlShiftTo(v,b),i.compareTo(b)>=0&&(i[i.t++]=1,i.subTo(b,i)),t.ONE.dlShiftTo(c,b),b.subTo(o,o);
o.t<c;
)o[o.t++]=0;
for(;
--v>=0;
){var S=i[--y]==f?this.DM:Math.floor(i[y]*p+(i[y-1]+d)*g);
if((i[y]+=o.am(0,S,i,v,0,c))<S)for(o.dlShiftTo(v,b),i.subTo(b,i);
i[y]<--S;
)i.subTo(b,i)}null!=r&&(i.drShiftTo(c,r),h!=u&&t.ZERO.subTo(r,r)),i.t=c,i.clamp(),a>0&&i.rShiftTo(a,i),h<0&&t.ZERO.subTo(i,i)}}},t.prototype.invDigit=function(){if(this.t<1)return 0;
var t=this[0];
if(0==(1&t))return 0;
var e=3&t;
return(e=(e=(e=(e=e*(2-(15&t)*e)&15)*(2-(255&t)*e)&255)*(2-((65535&t)*e&65535))&65535)*(2-t*e%this.DV)%this.DV)>0?this.DV-e:-e},t.prototype.isEven=function(){return 0==(this.t>0?1&this[0]:this.s)},t.prototype.exp=function(e,r){if(e>4294967295||e<1)return t.ONE;
var i=m(),n=m(),s=r.convert(this),o=_(e)-1;
for(s.copyTo(i);
--o>=0;
)if(r.sqrTo(i,n),(e&1<<o)>0)r.mulTo(n,s,i);
else{var h=i;
i=n,n=h}return r.revert(i)},t.prototype.chunkSize=function(t){return Math.floor(Math.LN2*this.DB/Math.log(t))},t.prototype.toRadix=function(t){if(null==t&&(t=10),0==this.signum()||t<2||t>36)return"0";
var e=this.chunkSize(t),r=Math.pow(t,e),i=x(r),n=m(),s=m(),o="";
for(this.divRemTo(i,n,s);
n.signum()>0;
)o=(r+s.intValue()).toString(t).substr(1)+o,n.divRemTo(i,n,s);
return s.intValue().toString(t)+o},t.prototype.fromRadix=function(e,r){this.fromInt(0),null==r&&(r=10);
for(var i=this.chunkSize(r),n=Math.pow(r,i),s=!1,o=0,h=0,u=0;
u<e.length;
++u){var a=w(e,u);
a<0?"-"==e.charAt(u)&&0==this.signum()&&(s=!0):(h=r*h+a,++o>=i&&(this.dMultiply(n),this.dAddOffset(h,0),o=0,h=0))}o>0&&(this.dMultiply(Math.pow(r,o)),this.dAddOffset(h,0)),s&&t.ZERO.subTo(this,this)},t.prototype.fromNumber=function(e,r,i){if("number"==typeof r)if(e<2)this.fromInt(1);
else for(this.fromNumber(e,i),this.testBit(e-1)||this.bitwiseTo(t.ONE.shiftLeft(e-1),c,this),this.isEven()&&this.dAddOffset(1,0);
!this.isProbablePrime(r);
)this.dAddOffset(2,0),this.bitLength()>e&&this.subTo(t.ONE.shiftLeft(e-1),this);
else{var n=[],s=7&e;
n.length=1+(e>>3),r.nextBytes(n),s>0?n[0]&=(1<<s)-1:n[0]=0,this.fromString(n,256)}},t.prototype.bitwiseTo=function(t,e,r){var i,n,s=Math.min(t.t,this.t);
for(i=0;
i<s;
++i)r[i]=e(this[i],t[i]);
if(t.t<this.t){for(n=t.s&this.DM,i=s;
i<this.t;
++i)r[i]=e(this[i],n);
r.t=this.t}else{for(n=this.s&this.DM,i=s;
i<t.t;
++i)r[i]=e(n,t[i]);
r.t=t.t}r.s=e(this.s,t.s),r.clamp()},t.prototype.changeBit=function(e,r){var i=t.ONE.shiftLeft(e);
return this.bitwiseTo(i,r,i),i},t.prototype.addTo=function(t,e){for(var r=0,i=0,n=Math.min(t.t,this.t);
r<n;
)i+=this[r]+t[r],e[r++]=i&this.DM,i>>=this.DB;
if(t.t<this.t){for(i+=t.s;
r<this.t;
)i+=this[r],e[r++]=i&this.DM,i>>=this.DB;
i+=this.s}else{for(i+=this.s;
r<t.t;
)i+=t[r],e[r++]=i&this.DM,i>>=this.DB;
i+=t.s}e.s=i<0?-1:0,i>0?e[r++]=i:i<-1&&(e[r++]=this.DV+i),e.t=r,e.clamp()},t.prototype.dMultiply=function(t){this[this.t]=this.am(0,t-1,this,0,0,this.t),++this.t,this.clamp()},t.prototype.dAddOffset=function(t,e){if(0!=t){for(;
this.t<=e;
)this[this.t++]=0;
for(this[e]+=t;
this[e]>=this.DV;
)this[e]-=this.DV,++e>=this.t&&(this[this.t++]=0),++this[e]}},t.prototype.multiplyLowerTo=function(t,e,r){var i=Math.min(this.t+t.t,e);
for(r.s=0,r.t=i;
i>0;
)r[--i]=0;
for(var n=r.t-this.t;
i<n;
++i)r[i+this.t]=this.am(0,t[i],r,i,0,this.t);
for(n=Math.min(t.t,e);
i<n;
++i)this.am(0,t[i],r,i,0,e-i);
r.clamp()},t.prototype.multiplyUpperTo=function(t,e,r){--e;
var i=r.t=this.t+t.t-e;
for(r.s=0;
--i>=0;
)r[i]=0;
for(i=Math.max(e-this.t,0);
i<t.t;
++i)r[this.t+i-e]=this.am(e-i,t[i],r,0,0,this.t+i-e);
r.clamp(),r.drShiftTo(1,r)},t.prototype.modInt=function(t){if(t<=0)return 0;
var e=this.DV%t,r=this.s<0?t-1:0;
if(this.t>0)if(0==e)r=this[0]%t;
else for(var i=this.t-1;
i>=0;
--i)r=(e*r+this[i])%t;
return r},t.prototype.millerRabin=function(e){var r=this.subtract(t.ONE),i=r.getLowestSetBit();
if(i<=0)return!1;
var n=r.shiftRight(i);
(e=e+1>>1)>l.length&&(e=l.length);
for(var s=m(),o=0;
o<e;
++o){s.fromInt(l[Math.floor(Math.random()*l.length)]);
var h=s.modPow(n,this);
if(0!=h.compareTo(t.ONE)&&0!=h.compareTo(r)){for(var u=1;
u++<i&&0!=h.compareTo(r);
)if(0==(h=h.modPowInt(2,this)).compareTo(t.ONE))return!1;
if(0!=h.compareTo(r))return!1}}return!0},t.prototype.square=function(){var t=m();
return this.squareTo(t),t},t.prototype.gcda=function(t,e){var r=this.s<0?this.negate():this.clone(),i=t.s<0?t.negate():t.clone();
if(r.compareTo(i)<0){var n=r;
r=i,i=n}var s=r.getLowestSetBit(),o=i.getLowestSetBit();
if(o<0)e(r);
else{s<o&&(o=s),o>0&&(r.rShiftTo(o,r),i.rShiftTo(o,i));
var h=function(){(s=r.getLowestSetBit())>0&&r.rShiftTo(s,r),(s=i.getLowestSetBit())>0&&i.rShiftTo(s,i),r.compareTo(i)>=0?(r.subTo(i,r),r.rShiftTo(1,r)):(i.subTo(r,i),i.rShiftTo(1,i)),r.signum()>0?setTimeout(h,0):(o>0&&i.lShiftTo(o,i),setTimeout((function(){e(i)}),0))};
setTimeout(h,10)}},t.prototype.fromNumberAsync=function(e,r,i,n){if("number"==typeof r)if(e<2)this.fromInt(1);
else{this.fromNumber(e,i),this.testBit(e-1)||this.bitwiseTo(t.ONE.shiftLeft(e-1),c,this),this.isEven()&&this.dAddOffset(1,0);
var s=this,o=function(){s.dAddOffset(2,0),s.bitLength()>e&&s.subTo(t.ONE.shiftLeft(e-1),s),s.isProbablePrime(r)?setTimeout((function(){n()}),0):setTimeout(o,0)};
setTimeout(o,0)}else{var h=[],u=7&e;
h.length=1+(e>>3),r.nextBytes(h),u>0?h[0]&=(1<<u)-1:h[0]=0,this.fromString(h,256)}},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"BigInteger",{enumerable:!0,configurable:!0,get:function(){return g}});
var d=function(){function t(){}return t.prototype.convert=function(t){return t},t.prototype.revert=function(t){return t},t.prototype.mulTo=function(t,e,r){t.multiplyTo(e,r)},t.prototype.sqrTo=function(t,e){t.squareTo(e)},t}(),y=function(){function t(t){this.m=t}return t.prototype.convert=function(t){return t.s<0||t.compareTo(this.m)>=0?t.mod(this.m):t},t.prototype.revert=function(t){return t},t.prototype.reduce=function(t){t.divRemTo(this.m,null,t)},t.prototype.mulTo=function(t,e,r){t.multiplyTo(e,r),this.reduce(r)},t.prototype.sqrTo=function(t,e){t.squareTo(e),this.reduce(e)},t}(),v=function(){function t(t){this.m=t,this.mp=t.invDigit(),this.mpl=32767&this.mp,this.mph=this.mp>>15,this.um=(1<<t.DB-15)-1,this.mt2=2*t.t}return t.prototype.convert=function(t){var e=m();
return t.abs().dlShiftTo(this.m.t,e),e.divRemTo(this.m,null,e),t.s<0&&e.compareTo(g.ZERO)>0&&this.m.subTo(e,e),e},t.prototype.revert=function(t){var e=m();
return t.copyTo(e),this.reduce(e),e},t.prototype.reduce=function(t){for(;
t.t<=this.mt2;
)t[t.t++]=0;
for(var e=0;
e<this.m.t;
++e){var r=32767&t[e],i=r*this.mpl+((r*this.mph+(t[e]>>15)*this.mpl&this.um)<<15)&t.DM;
for(t[r=e+this.m.t]+=this.m.am(0,i,t,e,0,this.m.t);
t[r]>=t.DV;
)t[r]-=t.DV,t[++r]++}t.clamp(),t.drShiftTo(this.m.t,t),t.compareTo(this.m)>=0&&t.subTo(this.m,t)},t.prototype.mulTo=function(t,e,r){t.multiplyTo(e,r),this.reduce(r)},t.prototype.sqrTo=function(t,e){t.squareTo(e),this.reduce(e)},t}(),b=function(){function t(t){this.m=t,this.r2=m(),this.q3=m(),g.ONE.dlShiftTo(2*t.t,this.r2),this.mu=this.r2.divide(t)}return t.prototype.convert=function(t){if(t.s<0||t.t>2*this.m.t)return t.mod(this.m);
if(t.compareTo(this.m)<0)return t;
var e=m();
return t.copyTo(e),this.reduce(e),e},t.prototype.revert=function(t){return t},t.prototype.reduce=function(t){for(t.drShiftTo(this.m.t-1,this.r2),t.t>this.m.t+1&&(t.t=this.m.t+1,t.clamp()),this.mu.multiplyUpperTo(this.r2,this.m.t+1,this.q3),this.m.multiplyLowerTo(this.q3,this.m.t+1,this.r2);
t.compareTo(this.r2)<0;
)t.dAddOffset(1,this.m.t+1);
for(t.subTo(this.r2,t);
t.compareTo(this.m)>=0;
)t.subTo(this.m,t)},t.prototype.mulTo=function(t,e,r){t.multiplyTo(e,r),this.reduce(r)},t.prototype.sqrTo=function(t,e){t.squareTo(e),this.reduce(e)},t}();
function m(){return new g(null)}r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.nbi=m,r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.parseBigInt=function(t,e){return new g(t,e)};
var S="undefined"!=typeof navigator;
S&&"Microsoft Internet Explorer"==navigator.appName?(g.prototype.am=function(t,e,r,i,n,s){for(var o=32767&e,h=e>>15;
--s>=0;
){var u=32767&this[t],a=this[t++]>>15,c=h*u+a*o;
n=((u=o*u+((32767&c)<<15)+r[i]+(1073741823&n))>>>30)+(c>>>15)+h*a+(n>>>30),r[i++]=1073741823&u}return n},i=30):S&&"Netscape"!=navigator.appName?(g.prototype.am=function(t,e,r,i,n,s){for(;
--s>=0;
){var o=e*this[t++]+r[i]+n;
n=Math.floor(o/67108864),r[i++]=67108863&o}return n},i=26):(g.prototype.am=function(t,e,r,i,n,s){for(var o=16383&e,h=e>>14;
--s>=0;
){var u=16383&this[t],a=this[t++]>>14,c=h*u+a*o;
n=((u=o*u+((16383&c)<<14)+r[i]+n)>>28)+(c>>14)+h*a,r[i++]=268435455&u}return n},i=28),g.prototype.DB=i,g.prototype.DM=(1<<i)-1,g.prototype.DV=1<<i,g.prototype.FV=Math.pow(2,52),g.prototype.F1=52-i,g.prototype.F2=2*i-52;
var T,E,D=[];
for(T="0".charCodeAt(0),E=0;
E<=9;
++E)D[T++]=E;
for(T="a".charCodeAt(0),E=10;
E<36;
++E)D[T++]=E;
for(T="A".charCodeAt(0),E=10;
E<36;
++E)D[T++]=E;
function w(t,e){var r=D[t.charCodeAt(e)];
return null==r?-1:r}function x(t){var e=m();
return e.fromInt(t),e}function _(t){var e,r=1;
return 0!=(e=t>>>16)&&(t=e,r+=16),0!=(e=t>>8)&&(t=e,r+=8),0!=(e=t>>4)&&(t=e,r+=4),0!=(e=t>>2)&&(t=e,r+=2),0!=(e=t>>1)&&(t=e,r+=1),r}r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.intAt=w,r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.nbv=x,r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.nbits=_,g.ZERO=x(0),g.ONE=x(1)}),(function(t){return r({"./util":1667461081099}[t],t)})),e(1667461081107,(function(t,e,r){var i,n,s=t("./prng4"),o=s.prng_newstate,h=s.rng_psize,u=null;
function a(){if(null==i){for(i=o();
n<h;
){var t=Math.floor(65536*Math.random());
u[n++]=255&t}for(i.init(u),n=0;
n<u.length;
++n)u[n]=0;
n=0}return i.next()}null==u&&(u=[],n=0);
var c=function(){function t(){}return t.prototype.nextBytes=function(t){for(var e=0;
e<t.length;
++e)t[e]=a()},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"SecureRandom",{enumerable:!0,configurable:!0,get:function(){return c}})}),(function(t){return r({"./prng4":1667461081108}[t],t)})),e(1667461081108,(function(t,e,r){var i=function(){function t(){this.i=0,this.j=0,this.S=[]}return t.prototype.init=function(t){var e,r,i;
for(e=0;
e<256;
++e)this.S[e]=e;
for(r=0,e=0;
e<256;
++e)r=r+this.S[e]+t[e%t.length]&255,i=this.S[e],this.S[e]=this.S[r],this.S[r]=i;
this.i=0,this.j=0},t.prototype.next=function(){var t;
return this.i=this.i+1&255,this.j=this.j+this.S[this.i]&255,t=this.S[this.i],this.S[this.i]=this.S[this.j],this.S[this.j]=t,this.S[t+this.S[this.i]&255]},t}();
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),Object.defineProperty(r,"Arcfour",{enumerable:!0,configurable:!0,get:function(){return i}}),r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.prng_newstate=function(){return new i},r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),r.rng_psize=256}),(function(t){return r({}[t],t)})),e(1667461081109,(function(t,e,r){var i=t("../jsbn/jsbn").BigInteger,n=t("./yahoo").YAHOO;

/**
     * @fileOverview
     * @name asn1-1.0.js
     * @author Kenji Urushima kenji.urushima@gmail.com
     * @version asn1 1.0.13 (2017-Jun-02)
     * @since jsrsasign 2.1
     * @license <a href="https://kjur.github.io/jsrsasign/license/">MIT License</a>
     */
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0});
var s=r.KJUR={};
void 0!==s.asn1&&s.asn1||(s.asn1={}),s.asn1.ASN1Util=new function(){this.integerToByteHex=function(t){var e=t.toString(16);
return e.length%2==1&&(e="0"+e),e},this.bigIntToMinTwosComplementsHex=function(t){var e=t.toString(16);
if("-"!=e.substr(0,1))e.length%2==1?e="0"+e:e.match(/^[0-7]/)||(e="00"+e);
else{var r=e.substr(1).length;
r%2==1?r+=1:e.match(/^[0-7]/)||(r+=2);
for(var n="",s=0;
s<r;
s++)n+="f";
e=new i(n,16).xor(t).add(i.ONE).toString(16).replace(/^-/,"")}return e},this.getPEMStringFromHex=function(t,e){return hextopem(t,e)},this.newObject=function(t){var e=s.asn1,r=e.DERBoolean,i=e.DERInteger,n=e.DERBitString,o=e.DEROctetString,h=e.DERNull,u=e.DERObjectIdentifier,a=e.DEREnumerated,c=e.DERUTF8String,f=e.DERNumericString,l=e.DERPrintableString,p=e.DERTeletexString,g=e.DERIA5String,d=e.DERUTCTime,y=e.DERGeneralizedTime,v=e.DERSequence,b=e.DERSet,m=e.DERTaggedObject,S=e.ASN1Util.newObject,T=Object.keys(t);
if(1!=T.length)throw"key of param shall be only one.";
var E=T[0];
if(-1==":bool:int:bitstr:octstr:null:oid:enum:utf8str:numstr:prnstr:telstr:ia5str:utctime:gentime:seq:set:tag:".indexOf(":"+E+":"))throw"undefined key: "+E;
if("bool"==E)return new r(t[E]);
if("int"==E)return new i(t[E]);
if("bitstr"==E)return new n(t[E]);
if("octstr"==E)return new o(t[E]);
if("null"==E)return new h(t[E]);
if("oid"==E)return new u(t[E]);
if("enum"==E)return new a(t[E]);
if("utf8str"==E)return new c(t[E]);
if("numstr"==E)return new f(t[E]);
if("prnstr"==E)return new l(t[E]);
if("telstr"==E)return new p(t[E]);
if("ia5str"==E)return new g(t[E]);
if("utctime"==E)return new d(t[E]);
if("gentime"==E)return new y(t[E]);
if("seq"==E){for(var D=t[E],w=[],x=0;
x<D.length;
x++){var _=S(D[x]);
w.push(_)}return new v({array:w})}if("set"==E){for(D=t[E],w=[],x=0;
x<D.length;
x++)_=S(D[x]),w.push(_);
return new b({array:w})}if("tag"==E){var O=t[E];
if("[object Array]"===Object.prototype.toString.call(O)&&3==O.length){var R=S(O[2]);
return new m({tag:O[0],explicit:O[1],obj:R})}var B={};
if(void 0!==O.explicit&&(B.explicit=O.explicit),void 0!==O.tag&&(B.tag=O.tag),void 0===O.obj)throw"obj shall be specified for 'tag'.";
return B.obj=S(O.obj),new m(B)}},this.jsonToASN1HEX=function(t){return this.newObject(t).getEncodedHex()}},s.asn1.ASN1Util.oidHexToInt=function(t){for(var e="",r=parseInt(t.substr(0,2),16),n=(e=Math.floor(r/40)+"."+r%40,""),s=2;
s<t.length;
s+=2){var o=("00000000"+parseInt(t.substr(s,2),16).toString(2)).slice(-8);
n+=o.substr(1,7),"0"==o.substr(0,1)&&(e=e+"."+new i(n,2).toString(10),n="")}return e},s.asn1.ASN1Util.oidIntToHex=function(t){var e=function(t){var e=t.toString(16);
return 1==e.length&&(e="0"+e),e},r=function(t){var r="",n=new i(t,10).toString(2),s=7-n.length%7;
7==s&&(s=0);
for(var o="",h=0;
h<s;
h++)o+="0";
for(n=o+n,h=0;
h<n.length-1;
h+=7){var u=n.substr(h,7);
h!=n.length-7&&(u="1"+u),r+=e(parseInt(u,2))}return r};
if(!t.match(/^[0-9.]+$/))throw"malformed oid string: "+t;
var n="",s=t.split("."),o=40*parseInt(s[0])+parseInt(s[1]);
n+=e(o),s.splice(0,2);
for(var h=0;
h<s.length;
h++)n+=r(s[h]);
return n},s.asn1.ASN1Object=function(){this.getLengthHexFromValue=function(){if(void 0===this.hV||null==this.hV)throw"this.hV is null or undefined.";
if(this.hV.length%2==1)throw"value hex must be even length: n="+"".length+",v="+this.hV;
var t=this.hV.length/2,e=t.toString(16);
if(e.length%2==1&&(e="0"+e),t<128)return e;
var r=e.length/2;
if(r>15)throw"ASN.1 length too long to represent by 8x: n = "+t.toString(16);
return(128+r).toString(16)+e},this.getEncodedHex=function(){return(null==this.hTLV||this.isModified)&&(this.hV=this.getFreshValueHex(),this.hL=this.getLengthHexFromValue(),this.hTLV=this.hT+this.hL+this.hV,this.isModified=!1),this.hTLV},this.getValueHex=function(){return this.getEncodedHex(),this.hV},this.getFreshValueHex=function(){return""}},s.asn1.DERAbstractString=function(t){s.asn1.DERAbstractString.superclass.constructor.call(this),this.getString=function(){return this.s},this.setString=function(t){this.hTLV=null,this.isModified=!0,this.s=t,this.hV=stohex(this.s)},this.setStringHex=function(t){this.hTLV=null,this.isModified=!0,this.s=null,this.hV=t},this.getFreshValueHex=function(){return this.hV},void 0!==t&&("string"==typeof t?this.setString(t):void 0!==t.str?this.setString(t.str):void 0!==t.hex&&this.setStringHex(t.hex))},n.lang.extend(s.asn1.DERAbstractString,s.asn1.ASN1Object),s.asn1.DERAbstractTime=function(t){s.asn1.DERAbstractTime.superclass.constructor.call(this),this.localDateToUTC=function(t){return utc=t.getTime()+6e4*t.getTimezoneOffset(),new Date(utc)},this.formatDate=function(t,e,r){var i=this.zeroPadding,n=this.localDateToUTC(t),s=String(n.getFullYear());
"utc"==e&&(s=s.substr(2,2));
var o=s+i(String(n.getMonth()+1),2)+i(String(n.getDate()),2)+i(String(n.getHours()),2)+i(String(n.getMinutes()),2)+i(String(n.getSeconds()),2);
if(!0===r){var h=n.getMilliseconds();
if(0!=h){var u=i(String(h),3);
o=o+"."+(u=u.replace(/[0]+$/,""))}}return o+"Z"},this.zeroPadding=function(t,e){return t.length>=e?t:new Array(e-t.length+1).join("0")+t},this.getString=function(){return this.s},this.setString=function(t){this.hTLV=null,this.isModified=!0,this.s=t,this.hV=stohex(t)},this.setByDateValue=function(t,e,r,i,n,s){var o=new Date(Date.UTC(t,e-1,r,i,n,s,0));
this.setByDate(o)},this.getFreshValueHex=function(){return this.hV}},n.lang.extend(s.asn1.DERAbstractTime,s.asn1.ASN1Object),s.asn1.DERAbstractStructured=function(t){s.asn1.DERAbstractString.superclass.constructor.call(this),this.setByASN1ObjectArray=function(t){this.hTLV=null,this.isModified=!0,this.asn1Array=t},this.appendASN1Object=function(t){this.hTLV=null,this.isModified=!0,this.asn1Array.push(t)},this.asn1Array=new Array,void 0!==t&&void 0!==t.array&&(this.asn1Array=t.array)},n.lang.extend(s.asn1.DERAbstractStructured,s.asn1.ASN1Object),s.asn1.DERBoolean=function(){s.asn1.DERBoolean.superclass.constructor.call(this),this.hT="01",this.hTLV="0101ff"},n.lang.extend(s.asn1.DERBoolean,s.asn1.ASN1Object),s.asn1.DERInteger=function(t){s.asn1.DERInteger.superclass.constructor.call(this),this.hT="02",this.setByBigInteger=function(t){this.hTLV=null,this.isModified=!0,this.hV=s.asn1.ASN1Util.bigIntToMinTwosComplementsHex(t)},this.setByInteger=function(t){var e=new i(String(t),10);
this.setByBigInteger(e)},this.setValueHex=function(t){this.hV=t},this.getFreshValueHex=function(){return this.hV},void 0!==t&&(void 0!==t.bigint?this.setByBigInteger(t.bigint):void 0!==t.int?this.setByInteger(t.int):"number"==typeof t?this.setByInteger(t):void 0!==t.hex&&this.setValueHex(t.hex))},n.lang.extend(s.asn1.DERInteger,s.asn1.ASN1Object),s.asn1.DERBitString=function(t){if(void 0!==t&&void 0!==t.obj){var e=s.asn1.ASN1Util.newObject(t.obj);
t.hex="00"+e.getEncodedHex()}s.asn1.DERBitString.superclass.constructor.call(this),this.hT="03",this.setHexValueIncludingUnusedBits=function(t){this.hTLV=null,this.isModified=!0,this.hV=t},this.setUnusedBitsAndHexValue=function(t,e){if(t<0||7<t)throw"unused bits shall be from 0 to 7: u = "+t;
var r="0"+t;
this.hTLV=null,this.isModified=!0,this.hV=r+e},this.setByBinaryString=function(t){var e=8-(t=t.replace(/0+$/,"")).length%8;
8==e&&(e=0);
for(var r=0;
r<=e;
r++)t+="0";
var i="";
for(r=0;
r<t.length-1;
r+=8){var n=t.substr(r,8),s=parseInt(n,2).toString(16);
1==s.length&&(s="0"+s),i+=s}this.hTLV=null,this.isModified=!0,this.hV="0"+e+i},this.setByBooleanArray=function(t){for(var e="",r=0;
r<t.length;
r++)1==t[r]?e+="1":e+="0";
this.setByBinaryString(e)},this.newFalseArray=function(t){for(var e=new Array(t),r=0;
r<t;
r++)e[r]=!1;
return e},this.getFreshValueHex=function(){return this.hV},void 0!==t&&("string"==typeof t&&t.toLowerCase().match(/^[0-9a-f]+$/)?this.setHexValueIncludingUnusedBits(t):void 0!==t.hex?this.setHexValueIncludingUnusedBits(t.hex):void 0!==t.bin?this.setByBinaryString(t.bin):void 0!==t.array&&this.setByBooleanArray(t.array))},n.lang.extend(s.asn1.DERBitString,s.asn1.ASN1Object),s.asn1.DEROctetString=function(t){if(void 0!==t&&void 0!==t.obj){var e=s.asn1.ASN1Util.newObject(t.obj);
t.hex=e.getEncodedHex()}s.asn1.DEROctetString.superclass.constructor.call(this,t),this.hT="04"},n.lang.extend(s.asn1.DEROctetString,s.asn1.DERAbstractString),s.asn1.DERNull=function(){s.asn1.DERNull.superclass.constructor.call(this),this.hT="05",this.hTLV="0500"},n.lang.extend(s.asn1.DERNull,s.asn1.ASN1Object),s.asn1.DERObjectIdentifier=function(t){var e=function(t){var e=t.toString(16);
return 1==e.length&&(e="0"+e),e},r=function(t){var r="",n=new i(t,10).toString(2),s=7-n.length%7;
7==s&&(s=0);
for(var o="",h=0;
h<s;
h++)o+="0";
for(n=o+n,h=0;
h<n.length-1;
h+=7){var u=n.substr(h,7);
h!=n.length-7&&(u="1"+u),r+=e(parseInt(u,2))}return r};
s.asn1.DERObjectIdentifier.superclass.constructor.call(this),this.hT="06",this.setValueHex=function(t){this.hTLV=null,this.isModified=!0,this.s=null,this.hV=t},this.setValueOidString=function(t){if(!t.match(/^[0-9.]+$/))throw"malformed oid string: "+t;
var i="",n=t.split("."),s=40*parseInt(n[0])+parseInt(n[1]);
i+=e(s),n.splice(0,2);
for(var o=0;
o<n.length;
o++)i+=r(n[o]);
this.hTLV=null,this.isModified=!0,this.s=null,this.hV=i},this.setValueName=function(t){var e=s.asn1.x509.OID.name2oid(t);
if(""===e)throw"DERObjectIdentifier oidName undefined: "+t;
this.setValueOidString(e)},this.getFreshValueHex=function(){return this.hV},void 0!==t&&("string"==typeof t?t.match(/^[0-2].[0-9.]+$/)?this.setValueOidString(t):this.setValueName(t):void 0!==t.oid?this.setValueOidString(t.oid):void 0!==t.hex?this.setValueHex(t.hex):void 0!==t.name&&this.setValueName(t.name))},n.lang.extend(s.asn1.DERObjectIdentifier,s.asn1.ASN1Object),s.asn1.DEREnumerated=function(t){s.asn1.DEREnumerated.superclass.constructor.call(this),this.hT="0a",this.setByBigInteger=function(t){this.hTLV=null,this.isModified=!0,this.hV=s.asn1.ASN1Util.bigIntToMinTwosComplementsHex(t)},this.setByInteger=function(t){var e=new i(String(t),10);
this.setByBigInteger(e)},this.setValueHex=function(t){this.hV=t},this.getFreshValueHex=function(){return this.hV},void 0!==t&&(void 0!==t.int?this.setByInteger(t.int):"number"==typeof t?this.setByInteger(t):void 0!==t.hex&&this.setValueHex(t.hex))},n.lang.extend(s.asn1.DEREnumerated,s.asn1.ASN1Object),s.asn1.DERUTF8String=function(t){s.asn1.DERUTF8String.superclass.constructor.call(this,t),this.hT="0c"},n.lang.extend(s.asn1.DERUTF8String,s.asn1.DERAbstractString),s.asn1.DERNumericString=function(t){s.asn1.DERNumericString.superclass.constructor.call(this,t),this.hT="12"},n.lang.extend(s.asn1.DERNumericString,s.asn1.DERAbstractString),s.asn1.DERPrintableString=function(t){s.asn1.DERPrintableString.superclass.constructor.call(this,t),this.hT="13"},n.lang.extend(s.asn1.DERPrintableString,s.asn1.DERAbstractString),s.asn1.DERTeletexString=function(t){s.asn1.DERTeletexString.superclass.constructor.call(this,t),this.hT="14"},n.lang.extend(s.asn1.DERTeletexString,s.asn1.DERAbstractString),s.asn1.DERIA5String=function(t){s.asn1.DERIA5String.superclass.constructor.call(this,t),this.hT="16"},n.lang.extend(s.asn1.DERIA5String,s.asn1.DERAbstractString),s.asn1.DERUTCTime=function(t){s.asn1.DERUTCTime.superclass.constructor.call(this,t),this.hT="17",this.setByDate=function(t){this.hTLV=null,this.isModified=!0,this.date=t,this.s=this.formatDate(this.date,"utc"),this.hV=stohex(this.s)},this.getFreshValueHex=function(){return void 0===this.date&&void 0===this.s&&(this.date=new Date,this.s=this.formatDate(this.date,"utc"),this.hV=stohex(this.s)),this.hV},void 0!==t&&(void 0!==t.str?this.setString(t.str):"string"==typeof t&&t.match(/^[0-9]{12}Z$/)?this.setString(t):void 0!==t.hex?this.setStringHex(t.hex):void 0!==t.date&&this.setByDate(t.date))},n.lang.extend(s.asn1.DERUTCTime,s.asn1.DERAbstractTime),s.asn1.DERGeneralizedTime=function(t){s.asn1.DERGeneralizedTime.superclass.constructor.call(this,t),this.hT="18",this.withMillis=!1,this.setByDate=function(t){this.hTLV=null,this.isModified=!0,this.date=t,this.s=this.formatDate(this.date,"gen",this.withMillis),this.hV=stohex(this.s)},this.getFreshValueHex=function(){return void 0===this.date&&void 0===this.s&&(this.date=new Date,this.s=this.formatDate(this.date,"gen",this.withMillis),this.hV=stohex(this.s)),this.hV},void 0!==t&&(void 0!==t.str?this.setString(t.str):"string"==typeof t&&t.match(/^[0-9]{14}Z$/)?this.setString(t):void 0!==t.hex?this.setStringHex(t.hex):void 0!==t.date&&this.setByDate(t.date),!0===t.millis&&(this.withMillis=!0))},n.lang.extend(s.asn1.DERGeneralizedTime,s.asn1.DERAbstractTime),s.asn1.DERSequence=function(t){s.asn1.DERSequence.superclass.constructor.call(this,t),this.hT="30",this.getFreshValueHex=function(){for(var t="",e=0;
e<this.asn1Array.length;
e++)t+=this.asn1Array[e].getEncodedHex();
return this.hV=t,this.hV}},n.lang.extend(s.asn1.DERSequence,s.asn1.DERAbstractStructured),s.asn1.DERSet=function(t){s.asn1.DERSet.superclass.constructor.call(this,t),this.hT="31",this.sortFlag=!0,this.getFreshValueHex=function(){for(var t=new Array,e=0;
e<this.asn1Array.length;
e++){var r=this.asn1Array[e];
t.push(r.getEncodedHex())}return 1==this.sortFlag&&t.sort(),this.hV=t.join(""),this.hV},void 0!==t&&void 0!==t.sortflag&&0==t.sortflag&&(this.sortFlag=!1)},n.lang.extend(s.asn1.DERSet,s.asn1.DERAbstractStructured),s.asn1.DERTaggedObject=function(t){s.asn1.DERTaggedObject.superclass.constructor.call(this),this.hT="a0",this.hV="",this.isExplicit=!0,this.asn1Object=null,this.setASN1Object=function(t,e,r){this.hT=e,this.isExplicit=t,this.asn1Object=r,this.isExplicit?(this.hV=this.asn1Object.getEncodedHex(),this.hTLV=null,this.isModified=!0):(this.hV=null,this.hTLV=r.getEncodedHex(),this.hTLV=this.hTLV.replace(/^../,e),this.isModified=!1)},this.getFreshValueHex=function(){return this.hV},void 0!==t&&(void 0!==t.tag&&(this.hT=t.tag),void 0!==t.explicit&&(this.isExplicit=t.explicit),void 0!==t.obj&&(this.asn1Object=t.obj,this.setASN1Object(this.isExplicit,this.hT,this.asn1Object)))},n.lang.extend(s.asn1.DERTaggedObject,s.asn1.ASN1Object)}),(function(t){return r({"../jsbn/jsbn":1667461081106,"./yahoo":1667461081110}[t],t)})),e(1667461081110,(function(t,e,r){
/*!
    Copyright (c) 2011, Yahoo! Inc. All rights reserved.
    Code licensed under the BSD License:
    http://developer.yahoo.com/yui/license.html
    version: 2.9.0
    */
r.__esModule||Object.defineProperty(r,"__esModule",{value:!0}),(r.YAHOO={}).lang={extend:function(t,e,r){if(!e||!t)throw new Error("YAHOO.lang.extend failed, please check that all dependencies are included.");
var i=function(){};
if(i.prototype=e.prototype,t.prototype=new i,t.prototype.constructor=t,t.superclass=e.prototype,e.prototype.constructor==Object.prototype.constructor&&(e.prototype.constructor=e),r){var n;
for(n in r)t.prototype[n]=r[n];
var s=function(){},o=["toString","valueOf"];
try{/MSIE/.test(navigator.userAgent)&&(s=function(t,e){for(n=0;
n<o.length;
n+=1){var r=o[n],i=e[r];
"function"==typeof i&&i!=Object.prototype[r]&&(t[r]=i)}})}catch(t){}s(t.prototype,r)}}}}),(function(t){return r({}[t],t)})),e(1667461081111,(function(t,e,r){e.exports={version:"3.2.1"}}),(function(t){return r({}[t],t)})),r(1667461081096));
